---
title: "R Package for the OpenCage API"
subtitle: "Forward and Reverse Geocoding"
author: "Maëlle Salmon"
date: "2020-10-06"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---




This package is an interface to the OpenCage API that allows forward and reverse geocoding. To use the package, you will need an API key. To get an API key for OpenCage geocoding, register at https://geocoder.opencagedata.com/pricing. The free API key provides up to 2,500 calls a day. For ease of use, save your API key as an environment variable as described at http://stat545.com/bit003_api-key-env-var.html.

Both functions of the package will conveniently look for your API key using `Sys.getenv("OPENCAGE_KEY")` so if your API key is an environment variable called "OPENCAGE_KEY" you don't need to input it manually.

# Geocoding

The [OpenCage](https://geocoder.opencagedata.com/) API supports forward and reverse geocoding. Sources of OpenCage are open geospatial data including OpenStreetMap, Yahoo! GeoPlanet, Natural Earth Data, Thematic Mapping, Ordnance Survey OpenSpace, Statistics New Zealand, Zillow, MaxMind, GeoNames, the US Census Bureau and Flickr's shapefiles plus a whole lot more besides. See [this page](https://geocoder.opencagedata.com/credits) for the full list of credits.

Both forward and reverse geocoding typically return multiple results. Regarding these multiple results, the API doc states, "In cases where the geocoder is able to find multiple matches, the geocoder will return multiple results. The confidence or coordinates for each result should be examined to determine whether each result from an ambiguous query is sufficiently high to warrant using a result or not. A good strategy to reduce ambiguity is to use the optional `bounds` parameter described below to limit the area searched." Multiple results might mean you get a result for the airport and a road when querying a city name, or results for cities with the same name in different countries.

Below are two simple examples.

## Forward geocoding

Forward geocoding is from placename to latitude and longitude tuplet(s).


```r
library("opencage")
output <- opencage_forward(placename = "Sarzeau")
print(output$time_stamp)
#> [1] "2020-10-06 22:12:31 CEST"
library("dplyr")
output$rate_info %>% knitr::kable()
```



| limit| remaining|reset               |
|-----:|---------:|:-------------------|
|  2500|      2308|2020-10-07 02:00:00 |

```r
output$results %>% knitr::kable()
```



|annotations.DMS.lat  |annotations.DMS.lng |annotations.MGRS |annotations.Maidenhead |annotations.Mercator.x |annotations.Mercator.y |annotations.OSM.edit_url                                                    |annotations.OSM.note_url                                                 |annotations.OSM.url                                                                 |annotations.UN_M49.regions.EUROPE |annotations.UN_M49.regions.FR |annotations.UN_M49.regions.WESTERN_EUROPE |annotations.UN_M49.regions.WORLD |annotations.UN_M49.statistical_groupings |annotations.callingcode |annotations.currency.decimal_mark |annotations.currency.html_entity |annotations.currency.iso_code |annotations.currency.iso_numeric |annotations.currency.name |annotations.currency.smallest_denomination |annotations.currency.subunit |annotations.currency.subunit_to_unit |annotations.currency.symbol |annotations.currency.symbol_first |annotations.currency.thousands_separator |annotations.flag         |annotations.geohash  |annotations.qibla |annotations.roadinfo.drive_on |annotations.roadinfo.speed_in |annotations.sun.rise.apparent |annotations.sun.rise.astronomical |annotations.sun.rise.civil |annotations.sun.rise.nautical |annotations.sun.set.apparent |annotations.sun.set.astronomical |annotations.sun.set.civil |annotations.sun.set.nautical |annotations.timezone.name |annotations.timezone.now_in_dst |annotations.timezone.offset_sec |annotations.timezone.offset_string |annotations.timezone.short_name |annotations.what3words.words |annotations.wikidata |bounds.northeast.lat |bounds.northeast.lng |bounds.southwest.lat |bounds.southwest.lng |components.ISO_3166-1_alpha-2 |components.ISO_3166-1_alpha-3 |components._category |components._type |components.city |components.continent |components.country |components.country_code |components.county |components.municipality |components.political_union |components.postcode |components.state |components.state_code |confidence |formatted                                       | geometry.lat| geometry.lng|annotations.roadinfo.road |components.hamlet |components.post_office |components.road |components.village |query   |
|:--------------------|:-------------------|:----------------|:----------------------|:----------------------|:----------------------|:---------------------------------------------------------------------------|:------------------------------------------------------------------------|:-----------------------------------------------------------------------------------|:---------------------------------|:-----------------------------|:-----------------------------------------|:--------------------------------|:----------------------------------------|:-----------------------|:---------------------------------|:--------------------------------|:-----------------------------|:--------------------------------|:-------------------------|:------------------------------------------|:----------------------------|:------------------------------------|:---------------------------|:---------------------------------|:----------------------------------------|:------------------------|:--------------------|:-----------------|:-----------------------------|:-----------------------------|:-----------------------------|:---------------------------------|:--------------------------|:-----------------------------|:----------------------------|:--------------------------------|:-------------------------|:----------------------------|:-------------------------|:-------------------------------|:-------------------------------|:----------------------------------|:-------------------------------|:----------------------------|:--------------------|:--------------------|:--------------------|:--------------------|:--------------------|:-----------------------------|:-----------------------------|:--------------------|:----------------|:---------------|:--------------------|:------------------|:-----------------------|:-----------------|:-----------------------|:--------------------------|:-------------------|:----------------|:---------------------|:----------|:-----------------------------------------------|------------:|------------:|:-------------------------|:-----------------|:----------------------|:---------------|:------------------|:-------|
|47° 31' 43.56984'' N |2° 45' 51.11892'' W |30TWT1774963954  |IN87om86hv             |-307709.303            |5997281.031            |https://www.openstreetmap.org/edit?relation=959447#map=17/47.52877/-2.76420 |https://www.openstreetmap.org/note/new#map=17/47.52877/-2.76420&layers=N |https://www.openstreetmap.org/?mlat=47.52877&mlon=-2.76420#map=17/47.52877/-2.76420 |150                               |250                           |155                                       |001                              |MEDC                                     |33                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1EB><U+0001F1F7> |gbqn3h75jkz3413tdw1f |112.34            |right                         |km/h                          |1601965080                    |1601958960                        |1601963280                 |1601961120                    |1602005940                   |1602012060                       |1602007740                |1602009900                   |Europe/Paris              |1                               |7200                            |+0200                              |CEST                            |gasp.jiggle.creamier         |Q128716              |47.5666788           |-2.6631197           |47.4840815           |-2.853616            |FR                            |FRA                           |place                |city             |Sarzeau         |Europe               |France             |fr                      |Morbihan          |Vannes                  |European Union             |56370               |Brittany         |BRE                   |6          |Sarzeau, Morbihan, France                       |     47.52877|    -2.764200|NA                        |NA                |NA                     |NA              |NA                 |Sarzeau |
|47° 31' 40.75680'' N |2° 46' 7.87116'' W  |30TWT1739963866  |IN87om76rr             |-308227.317            |5997152.602            |https://www.openstreetmap.org/edit?node=846574100#map=17/47.52799/-2.76885  |https://www.openstreetmap.org/note/new#map=17/47.52799/-2.76885&layers=N |https://www.openstreetmap.org/?mlat=47.52799&mlon=-2.76885#map=17/47.52799/-2.76885 |150                               |250                           |155                                       |001                              |MEDC                                     |33                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1EB><U+0001F1F7> |gbqn2upy9517z9gpwc3y |112.34            |right                         |km/h                          |1601965080                    |1601958960                        |1601963280                 |1601961120                    |1602005940                   |1602012060                       |1602007740                |1602009900                   |Europe/Paris              |1                               |7200                            |+0200                              |CEST                            |classics.catacomb.shop       |NA                   |47.528038            |-2.7688031           |47.527938            |-2.7689031           |FR                            |FRA                           |government           |post_office      |NA              |Europe               |France             |fr                      |Morbihan          |Vannes                  |European Union             |56370               |Brittany         |BRE                   |9          |Sarzeau, Rue de la Poste, 56370 Sarzeau, France |     47.52799|    -2.768853|Rue de la Poste           |Kergroëz          |Sarzeau                |Rue de la Poste |Sarzeau            |Sarzeau |

## Reverse geocoding

Reverse geocoding is from latitude and longitude to placename(s).
T

```r
output2 <- opencage_reverse(latitude = 51.5034070,
                            longitude = -0.1275920)
print(output2$time_stamp)
#> [1] "2020-10-06 22:12:32 CEST"
output2$rate_info %>% knitr::kable()
```



| limit| remaining|reset               |
|-----:|---------:|:-------------------|
|  2500|      2307|2020-10-07 02:00:00 |

```r
output2$results %>% knitr::kable()
```



|annotations.DMS.lat  |annotations.DMS.lng |annotations.MGRS |annotations.Maidenhead |annotations.Mercator.x |annotations.Mercator.y |annotations.OSM.edit_url                                                     |annotations.OSM.note_url                                                 |annotations.OSM.url                                                                 |annotations.UN_M49.regions.EUROPE |annotations.UN_M49.regions.GB |annotations.UN_M49.regions.NORTHERN_EUROPE |annotations.UN_M49.regions.WORLD |annotations.UN_M49.statistical_groupings |annotations.callingcode |annotations.currency.decimal_mark |annotations.currency.html_entity |annotations.currency.iso_code |annotations.currency.iso_numeric |annotations.currency.name |annotations.currency.smallest_denomination |annotations.currency.subunit |annotations.currency.subunit_to_unit |annotations.currency.symbol |annotations.currency.symbol_first |annotations.currency.thousands_separator |annotations.flag         |annotations.geohash  |annotations.qibla |annotations.roadinfo.drive_on |annotations.roadinfo.road |annotations.roadinfo.speed_in |annotations.sun.rise.apparent |annotations.sun.rise.astronomical |annotations.sun.rise.civil |annotations.sun.rise.nautical |annotations.sun.set.apparent |annotations.sun.set.astronomical |annotations.sun.set.civil |annotations.sun.set.nautical |annotations.timezone.name |annotations.timezone.now_in_dst |annotations.timezone.offset_sec |annotations.timezone.offset_string |annotations.timezone.short_name |annotations.what3words.words |annotations.wikidata |bounds.northeast.lat |bounds.northeast.lng |bounds.southwest.lat |bounds.southwest.lng |components.ISO_3166-1_alpha-2 |components.ISO_3166-1_alpha-3 |components._category |components._type |components.city |components.continent |components.country |components.country_code |components.county |components.county_code |components.house_number |components.postcode |components.quarter |components.road |components.state |components.state_code |components.state_district |components.suburb |components.tourism      |confidence |formatted                                                                                | geometry.lat| geometry.lng|query               |
|:--------------------|:-------------------|:----------------|:----------------------|:----------------------|:----------------------|:----------------------------------------------------------------------------|:------------------------------------------------------------------------|:-----------------------------------------------------------------------------------|:---------------------------------|:-----------------------------|:------------------------------------------|:--------------------------------|:----------------------------------------|:-----------------------|:---------------------------------|:--------------------------------|:-----------------------------|:--------------------------------|:-------------------------|:------------------------------------------|:----------------------------|:------------------------------------|:---------------------------|:---------------------------------|:----------------------------------------|:------------------------|:--------------------|:-----------------|:-----------------------------|:-------------------------|:-----------------------------|:-----------------------------|:---------------------------------|:--------------------------|:-----------------------------|:----------------------------|:--------------------------------|:-------------------------|:----------------------------|:-------------------------|:-------------------------------|:-------------------------------|:----------------------------------|:-------------------------------|:----------------------------|:--------------------|:--------------------|:--------------------|:--------------------|:--------------------|:-----------------------------|:-----------------------------|:--------------------|:----------------|:---------------|:--------------------|:------------------|:-----------------------|:-----------------|:----------------------|:-----------------------|:-------------------|:------------------|:---------------|:----------------|:---------------------|:-------------------------|:-----------------|:-----------------------|:----------|:----------------------------------------------------------------------------------------|------------:|------------:|:-------------------|
|51° 30' 12.38472'' N |0° 7' 39.74952'' E  |30UXC9933909723  |IO91wm40qt             |-14216.413             |6677371.368            |https://www.openstreetmap.org/edit?relation=1879842#map=17/51.50344/-0.12771 |https://www.openstreetmap.org/note/new#map=17/51.50344/-0.12771&layers=N |https://www.openstreetmap.org/?mlat=51.50344&mlon=-0.12771#map=17/51.50344/-0.12771 |150                               |826                           |154                                        |001                              |MEDC                                     |44                      |.                                 |&#x00A3;                         |GBP                           |826                              |British Pound             |1                                          |Penny                        |100                                  |£                           |1                                 |,                                        |<U+0001F1EC><U+0001F1E7> |gcpuvpgj21ju5qmwdd59 |118.98            |left                          |Downing Street            |mph                           |1601964660                    |1601958000                        |1601962680                 |1601960340                    |1602005100                   |1602011760                       |1602007080                |1602009420                   |Europe/London             |1                               |3600                            |+0100                              |BST                             |onions.toned.active          |Q169101              |51.5036483           |-0.1273038           |51.5032573           |-0.1278356           |GB                            |GBR                           |unknown              |tourism          |London          |Europe               |United Kingdom     |gb                      |Westminster       |WSM                    |10                      |SW1A 2AA            |Westminster        |Downing Street  |England          |ENG                   |Greater London            |Covent Garden     |Prime Minister’s Office |9          |Prime Minister’s Office, Westminster, 10 Downing Street, London SW1A 2AA, United Kingdom |     51.50344|   -0.1277082|51.503407,-0.127592 |

## Output

For both `opencage_forward` and `opencage_reverse` functions, the package returns a list with a time stamp for the query, the total number of results, a data.frame (`dplyr tbl_df`) with information about the remaining calls to the API unless you have an unlimited account, and a data.frame (`dplyr tbl_df`) with the results corresponding to your query. You can find longitude and latitude for each results as `geometry.lat` and `geometry.lng`. Other information includes country and country information, time of sunset and sunrise, geohash (a geocoding system identifying a point with a single string, as explained in many more details [here](https://www.elastic.co/guide/en/elasticsearch/guide/current/geohashes.html) and [here](https://en.wikipedia.org/wiki/Geohash); for pure conversion between longitude/latitude and geohashes, see [this package](https://github.com/Ironholds/geohash)).  Depending on the data available in the API for the results one gets different columns; there can be a lot to explore!

## Parameters

Optional parameters of both `opencage_forward` and `opencage_reverse` can make the query more precise:

* `bounds`: Provides the geocoder with a hint to the region that the query resides in. This value will restrict the possible results to the supplied region. The bounds parameter should be specified as 4 coordinate points forming the south-west and north-east corners of a bounding box. For example, `bounds = c(-0.563160, 51.280430, 0.278970, 51.683979)` (min long, min lat, max long, max lat).

Below is an example of the use of `bounds` where the rectangle given in the second call does not include Europe so that we don't get results for Berlin in Germany.


```r
results1 <- opencage_forward(placename = "Berlin")
results1$results %>% knitr::kable()
```



|annotations.DMS.lat  |annotations.DMS.lng  |annotations.MGRS |annotations.Maidenhead |annotations.Mercator.x |annotations.Mercator.y |annotations.OSM.edit_url                                                       |annotations.OSM.note_url                                                  |annotations.OSM.url                                                                   |annotations.UN_M49.regions.DE |annotations.UN_M49.regions.EUROPE |annotations.UN_M49.regions.WESTERN_EUROPE |annotations.UN_M49.regions.WORLD |annotations.UN_M49.statistical_groupings |annotations.callingcode |annotations.currency.decimal_mark |annotations.currency.html_entity |annotations.currency.iso_code |annotations.currency.iso_numeric |annotations.currency.name |annotations.currency.smallest_denomination |annotations.currency.subunit |annotations.currency.subunit_to_unit |annotations.currency.symbol |annotations.currency.symbol_first |annotations.currency.thousands_separator |annotations.flag         |annotations.geohash  |annotations.qibla |annotations.roadinfo.drive_on |annotations.roadinfo.speed_in |annotations.sun.rise.apparent |annotations.sun.rise.astronomical |annotations.sun.rise.civil |annotations.sun.rise.nautical |annotations.sun.set.apparent |annotations.sun.set.astronomical |annotations.sun.set.civil |annotations.sun.set.nautical |annotations.timezone.name |annotations.timezone.now_in_dst |annotations.timezone.offset_sec |annotations.timezone.offset_string |annotations.timezone.short_name |annotations.what3words.words |annotations.wikidata |bounds.northeast.lat |bounds.northeast.lng |bounds.southwest.lat |bounds.southwest.lng |components.ISO_3166-1_alpha-2 |components.ISO_3166-1_alpha-3 |components._category |components._type |components.city |components.continent |components.country       |components.country_code |components.political_union |components.state |components.state_code |confidence |formatted                                                      | geometry.lat| geometry.lng|annotations.FIPS.county |annotations.FIPS.state |annotations.UN_M49.regions.AMERICAS |annotations.UN_M49.regions.NORTHERN_AMERICA |annotations.UN_M49.regions.US |annotations.currency.alternate_symbols |annotations.currency.disambiguate_symbol |components.county |components.postcode |components.suburb      |annotations.UN_M49.regions.FR |annotations.roadinfo.road |components.municipality |components.neighbourhood |components.railway |components.road |query  |
|:--------------------|:--------------------|:----------------|:----------------------|:----------------------|:----------------------|:------------------------------------------------------------------------------|:-------------------------------------------------------------------------|:-------------------------------------------------------------------------------------|:-----------------------------|:---------------------------------|:-----------------------------------------|:--------------------------------|:----------------------------------------|:-----------------------|:---------------------------------|:--------------------------------|:-----------------------------|:--------------------------------|:-------------------------|:------------------------------------------|:----------------------------|:------------------------------------|:---------------------------|:---------------------------------|:----------------------------------------|:------------------------|:--------------------|:-----------------|:-----------------------------|:-----------------------------|:-----------------------------|:---------------------------------|:--------------------------|:-----------------------------|:----------------------------|:--------------------------------|:-------------------------|:----------------------------|:-------------------------|:-------------------------------|:-------------------------------|:----------------------------------|:-------------------------------|:----------------------------|:--------------------|:--------------------|:--------------------|:--------------------|:--------------------|:-----------------------------|:-----------------------------|:--------------------|:----------------|:---------------|:--------------------|:------------------------|:-----------------------|:--------------------------|:----------------|:---------------------|:----------|:--------------------------------------------------------------|------------:|------------:|:-----------------------|:----------------------|:-----------------------------------|:-------------------------------------------|:-----------------------------|:--------------------------------------|:----------------------------------------|:-----------------|:-------------------|:----------------------|:-----------------------------|:-------------------------|:-----------------------|:------------------------|:------------------|:---------------|:------|
|52° 31' 1.33140'' N  |13° 23' 19.89564'' E |33UUU9067619766  |JO62qm64pc             |1490441.066            |6860227.862            |https://www.openstreetmap.org/edit?relation=62422#map=17/52.51704/13.38886     |https://www.openstreetmap.org/note/new#map=17/52.51704/13.38886&layers=N  |https://www.openstreetmap.org/?mlat=52.51704&mlon=13.38886#map=17/52.51704/13.38886   |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u33db8mmzj1t355u0c0j |136.66            |right                         |km/h                          |1601961480                    |1601954640                        |1601959440                 |1601957040                    |1602001800                   |1602008640                       |1602003840                |1602006240                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |third.gurgled.such           |Q64                  |52.6755087           |13.7611609           |52.3382448           |13.088345            |DE                            |DEU                           |place                |city             |Berlin          |Europe               |Germany                  |de                      |European Union             |Berlin           |BE                    |2          |Berlin, Germany                                                |     52.51704|    13.388860|NA                      |NA                     |NA                                  |NA                                          |NA                            |NA                                     |NA                                       |NA                |NA                  |NA                     |NA                            |NA                        |NA                      |NA                       |NA                 |NA              |Berlin |
|44° 28' 8.65560'' N  |71° 11' 6.81360'' W  |19TCK2618626296  |FN44jl72sn             |-7924303.11            |5508377.717            |https://www.openstreetmap.org/edit?relation=170184#map=17/44.46907/-71.18523   |https://www.openstreetmap.org/note/new#map=17/44.46907/-71.18523&layers=N |https://www.openstreetmap.org/?mlat=44.46907&mlon=-71.18523#map=17/44.46907/-71.18523 |NA                            |NA                                |NA                                        |001                              |MEDC                                     |1                       |.                                 |$                                |USD                           |840                              |United States Dollar      |1                                          |Cent                         |100                                  |$                           |1                                 |,                                        |<U+0001F1FA><U+0001F1F8> |drvkupke058m4sb6360c |60.36             |right                         |mph                           |1601981400                    |1601975640                        |1601979660                 |1601977680                    |1602022440                   |1602028200                       |1602024180                |1602026220                   |America/New_York          |1                               |-14400                          |-0400                              |EDT                             |strong.clean.crib            |Q821244              |44.528436            |-71.123642           |44.445057            |-71.397858           |US                            |USA                           |place                |city             |Berlin          |North America        |United States of America |us                      |NA                         |New Hampshire    |NH                    |5          |Berlin, New Hampshire, United States of America                |     44.46907|   -71.185226|33007                   |33                     |019                                 |021                                         |840                           |US$                                    |US$                                      |Coos County       |03570               |NA                     |NA                            |NA                        |NA                      |NA                       |NA                 |NA              |Berlin |
|39° 45' 32.17932'' N |89° 54' 11.38860'' W |16SBK5129805033  |EM59bs12od             |-10007974.382          |4803640.851            |https://www.openstreetmap.org/edit?relation=126290#map=17/39.75894/-89.90316   |https://www.openstreetmap.org/note/new#map=17/39.75894/-89.90316&layers=N |https://www.openstreetmap.org/?mlat=39.75894&mlon=-89.90316#map=17/39.75894/-89.90316 |NA                            |NA                                |NA                                        |001                              |MEDC                                     |1                       |.                                 |$                                |USD                           |840                              |United States Dollar      |1                                          |Cent                         |100                                  |$                           |1                                 |,                                        |<U+0001F1FA><U+0001F1F8> |dp044jys87qe8cu91khu |47.27             |right                         |mph                           |1601985720                    |1601980380                        |1601984160                 |1601982240                    |1602027120                   |1601946060                       |1602028740                |1601944200                   |America/Chicago           |1                               |-18000                          |-0500                              |CDT                             |scouting.forum.whispering    |Q2504681             |39.764932            |-89.893165           |39.750371            |-89.912101           |US                            |USA                           |place                |city             |Berlin          |North America        |United States of America |us                      |NA                         |Illinois         |IL                    |8          |Berlin, Illinois, United States of America                     |     39.75894|   -89.903164|17167                   |17                     |019                                 |021                                         |840                           |US$                                    |US$                                      |Sangamon County   |NA                  |NA                     |NA                            |NA                        |NA                      |NA                       |NA                 |NA              |Berlin |
|41° 37' 17.35680'' N |72° 44' 44.34684'' W |18TXM8780710206  |FN31po09md             |-8098008.927           |5076059.694            |https://www.openstreetmap.org/edit?relation=11042445#map=17/41.62149/-72.74565 |https://www.openstreetmap.org/note/new#map=17/41.62149/-72.74565&layers=N |https://www.openstreetmap.org/?mlat=41.62149&mlon=-72.74565#map=17/41.62149/-72.74565 |NA                            |NA                                |NA                                        |001                              |MEDC                                     |1                       |.                                 |$                                |USD                           |840                              |United States Dollar      |1                                          |Cent                         |100                                  |$                           |1                                 |,                                        |<U+0001F1FA><U+0001F1F8> |drkkb8unxrwqyhztwm4q |59.3              |right                         |mph                           |1601981700                    |1601976180                        |1601980020                 |1601978100                    |1602022920                   |1602028440                       |1602024600                |1602026520                   |America/New_York          |1                               |-14400                          |-0400                              |EDT                             |frosts.crowds.reef           |Q821199              |41.6527197           |-72.7111349          |41.554197            |-72.8402567          |US                            |USA                           |place                |city             |Berlin          |North America        |United States of America |us                      |NA                         |Connecticut      |CT                    |6          |Berlin, Connecticut, United States of America                  |     41.62149|   -72.745652|09003                   |09                     |019                                 |021                                         |840                           |US$                                    |US$                                      |Hartford County   |NA                  |NA                     |NA                            |NA                        |NA                      |NA                       |NA                 |NA              |Berlin |
|38° 19' 21.41544'' N |75° 13' 3.68112'' W  |18SVH8097141633  |FM28jh37vk             |-8373194.86            |4598602.233            |https://www.openstreetmap.org/edit?relation=133689#map=17/38.32262/-75.21769   |https://www.openstreetmap.org/note/new#map=17/38.32262/-75.21769&layers=N |https://www.openstreetmap.org/?mlat=38.32262&mlon=-75.21769#map=17/38.32262/-75.21769 |NA                            |NA                                |NA                                        |001                              |MEDC                                     |1                       |.                                 |$                                |USD                           |840                              |United States Dollar      |1                                          |Cent                         |100                                  |$                           |1                                 |,                                        |<U+0001F1FA><U+0001F1F8> |dqfd02kjkv3c6dwm8g5s |57.81             |right                         |mph                           |1601982180                    |1601976900                        |1601980560                 |1601978760                    |1602023640                   |1601942460                       |1602025200                |1602027060                   |America/New_York          |1                               |-14400                          |-0400                              |EDT                             |floral.evenly.shortwave      |Q614184              |38.355184            |-75.1879942          |38.308406            |-75.234794           |US                            |USA                           |place                |city             |Berlin          |North America        |United States of America |us                      |NA                         |Maryland         |MD                    |7          |Berlin, Maryland, United States of America                     |     38.32262|   -75.217689|24047                   |24                     |019                                 |021                                         |840                           |US$                                    |US$                                      |Worcester County  |NA                  |NA                     |NA                            |NA                        |NA                      |NA                       |NA                 |NA              |Berlin |
|44° 12' 36.27324'' N |72° 36' 12.25764'' W |18TXP9146797998  |FN34qf70ok             |-8082174.068           |5468204.6              |https://www.openstreetmap.org/edit?relation=8898132#map=17/44.21008/-72.60340  |https://www.openstreetmap.org/note/new#map=17/44.21008/-72.60340&layers=N |https://www.openstreetmap.org/?mlat=44.21008&mlon=-72.60340#map=17/44.21008/-72.60340 |NA                            |NA                                |NA                                        |001                              |MEDC                                     |1                       |.                                 |$                                |USD                           |840                              |United States Dollar      |1                                          |Cent                         |100                                  |$                           |1                                 |,                                        |<U+0001F1FA><U+0001F1F8> |dru7eb5y653rny3vp3ww |59.37             |right                         |mph                           |1601981760                    |1601976000                        |1601980020                 |1601978040                    |1602022800                   |1602028560                       |1602024540                |1602026520                   |America/New_York          |1                               |-14400                          |-0400                              |EDT                             |grooves.fearfully.classic    |Q821245              |44.2719667           |-72.5197921          |44.1547824           |-72.6836842          |US                            |USA                           |place                |city             |Berlin          |North America        |United States of America |us                      |NA                         |Vermont          |VT                    |6          |Berlin, Vermont, United States of America                      |     44.21008|   -72.603405|50023                   |50                     |019                                 |021                                         |840                           |US$                                    |US$                                      |Washington County |NA                  |NA                     |NA                            |NA                        |NA                      |NA                       |NA                 |NA              |Berlin |
|46° 22' 42.89628'' N |98° 29' 23.34588'' W |14TNS3923436238  |EN06sj10fu             |-10963836.421          |5810280.584            |https://www.openstreetmap.org/edit?relation=181615#map=17/46.37858/-98.48982   |https://www.openstreetmap.org/note/new#map=17/46.37858/-98.48982&layers=N |https://www.openstreetmap.org/?mlat=46.37858&mlon=-98.48982#map=17/46.37858/-98.48982 |NA                            |NA                                |NA                                        |001                              |MEDC                                     |1                       |.                                 |$                                |USD                           |840                              |United States Dollar      |1                                          |Cent                         |100                                  |$                           |1                                 |,                                        |<U+0001F1FA><U+0001F1F8> |cb1zyfcyufkesxxw9ch5 |39.34             |right                         |mph                           |1601988060                    |1601982060                        |1601986260                 |1601984160                    |1601942520                   |1601948460                       |1601944320                |1601946360                   |America/Chicago           |1                               |-18000                          |-0500                              |CDT                             |adults.allocation.ironclad   |Q821229              |46.380854            |-98.484052           |46.376668            |-98.494593           |US                            |USA                           |place                |neighbourhood    |NA              |North America        |United States of America |us                      |NA                         |North Dakota     |ND                    |9          |Berlin, LaMoure County, North Dakota, United States of America |     46.37858|   -98.489818|38045                   |38                     |019                                 |021                                         |840                           |US$                                    |US$                                      |LaMoure County    |NA                  |Berlin                 |NA                            |NA                        |NA                      |NA                       |NA                 |NA              |Berlin |
|39° 47' 28.41432'' N |74° 55' 44.59296'' W |18SWK0607404588  |FM29ms89mv             |-8341064.092           |4808298.871            |https://www.openstreetmap.org/edit?relation=170680#map=17/39.79123/-74.92905   |https://www.openstreetmap.org/note/new#map=17/39.79123/-74.92905&layers=N |https://www.openstreetmap.org/?mlat=39.79123&mlon=-74.92905#map=17/39.79123/-74.92905 |NA                            |NA                                |NA                                        |001                              |MEDC                                     |1                       |.                                 |$                                |USD                           |840                              |United States Dollar      |1                                          |Cent                         |100                                  |$                           |1                                 |,                                        |<U+0001F1FA><U+0001F1F8> |dr4dqgy2dw0juru53e8c |57.91             |right                         |mph                           |1601982180                    |1601976780                        |1601980560                 |1601978640                    |1602023520                   |1601942460                       |1602025140                |1602027000                   |America/New_York          |1                               |-14400                          |-0400                              |EDT                             |verdict.rushes.upgrading     |Q1086827             |39.8091498           |-74.907959           |39.77601             |-74.966113           |US                            |USA                           |place                |city             |Berlin          |North America        |United States of America |us                      |NA                         |New Jersey       |NJ                    |7          |Berlin, New Jersey, United States of America                   |     39.79123|   -74.929054|34007                   |34                     |019                                 |021                                         |840                           |US$                                    |US$                                      |Camden County     |NA                  |NA                     |NA                            |NA                        |NA                      |NA                       |NA                 |NA              |Berlin |
|42° 23' 2.04900'' N  |71° 37' 57.15660'' W |19TBG8328795759  |FN42ej42cd             |-7974098.267           |5189849.26             |https://www.openstreetmap.org/edit?relation=1844156#map=17/42.38390/-71.63254  |https://www.openstreetmap.org/note/new#map=17/42.38390/-71.63254&layers=N |https://www.openstreetmap.org/?mlat=42.38390&mlon=-71.63254#map=17/42.38390/-71.63254 |NA                            |NA                                |NA                                        |001                              |MEDC                                     |1                       |.                                 |$                                |USD                           |840                              |United States Dollar      |1                                          |Cent                         |100                                  |$                           |1                                 |,                                        |<U+0001F1FA><U+0001F1F8> |drt11gyb0u04x1wbc76t |60.04             |right                         |mph                           |1601981460                    |1601975880                        |1601979780                 |1601977800                    |1602022620                   |1602028200                       |1602024300                |1602026280                   |America/New_York          |1                               |-14400                          |-0400                              |EDT                             |wires.examination.boom       |Q524646              |42.4182323           |-71.5801342          |42.3504652           |-71.6787662          |US                            |USA                           |place                |city             |Berlin          |North America        |United States of America |us                      |NA                         |Massachusetts    |MA                    |7          |Berlin, Massachusetts, United States of America                |     42.38390|   -71.632543|25027                   |25                     |019                                 |021                                         |840                           |US$                                    |US$                                      |Worcester County  |01503               |NA                     |NA                            |NA                        |NA                      |NA                       |NA                 |NA              |Berlin |
|48° 52' 46.57332'' N |2° 19' 37.28676'' E  |31UDQ5065814290  |JN18dv91fc             |259043.138             |6222251.062            |https://www.openstreetmap.org/edit?node=331514770#map=17/48.87960/2.32702      |https://www.openstreetmap.org/note/new#map=17/48.87960/2.32702&layers=N   |https://www.openstreetmap.org/?mlat=48.87960&mlon=2.32702#map=17/48.87960/2.32702     |NA                            |150                               |155                                       |001                              |MEDC                                     |33                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1EB><U+0001F1F7> |u09whfq2rddctbd43kyn |119.16            |right                         |km/h                          |1601963940                    |1601957640                        |1601962080                 |1601959860                    |1602004680                   |1602010920                       |1602006540                |1602008700                   |Europe/Paris              |1                               |7200                            |+0200                              |CEST                            |spotted.handbook.custard     |Q1866688             |48.8796537           |2.3270741            |48.8795537           |2.3269741            |FR                            |FRA                           |transportation       |railway          |Paris           |Europe               |France                   |fr                      |European Union             |Ile-de-France    |IDF                   |9          |Liège, Rue d'Amsterdam, 75009 Paris, France                    |     48.87960|     2.327024|NA                      |NA                     |NA                                  |NA                                          |NA                            |NA                                     |NA                                       |Paris             |75009               |Quartier Saint-Georges |250                           |Rue d'Amsterdam           |Paris                   |Quartier Saint-Georges   |Liège              |Rue d'Amsterdam |Berlin |

```r
results2 <- opencage_forward(placename = "Berlin",
                             bounds = c(-90,38,0, 45))
results2$results %>% knitr::kable()
```



|annotations.DMS.lat  |annotations.DMS.lng  |annotations.FIPS.county |annotations.FIPS.state |annotations.MGRS |annotations.Maidenhead |annotations.Mercator.x |annotations.Mercator.y |annotations.OSM.edit_url                                                       |annotations.OSM.note_url                                                  |annotations.OSM.url                                                                   |annotations.UN_M49.regions.AMERICAS |annotations.UN_M49.regions.NORTHERN_AMERICA |annotations.UN_M49.regions.US |annotations.UN_M49.regions.WORLD |annotations.UN_M49.statistical_groupings |annotations.callingcode |annotations.currency.alternate_symbols |annotations.currency.decimal_mark |annotations.currency.disambiguate_symbol |annotations.currency.html_entity |annotations.currency.iso_code |annotations.currency.iso_numeric |annotations.currency.name |annotations.currency.smallest_denomination |annotations.currency.subunit |annotations.currency.subunit_to_unit |annotations.currency.symbol |annotations.currency.symbol_first |annotations.currency.thousands_separator |annotations.flag         |annotations.geohash  |annotations.qibla |annotations.roadinfo.drive_on |annotations.roadinfo.speed_in |annotations.sun.rise.apparent |annotations.sun.rise.astronomical |annotations.sun.rise.civil |annotations.sun.rise.nautical |annotations.sun.set.apparent |annotations.sun.set.astronomical |annotations.sun.set.civil |annotations.sun.set.nautical |annotations.timezone.name |annotations.timezone.now_in_dst |annotations.timezone.offset_sec |annotations.timezone.offset_string |annotations.timezone.short_name |annotations.what3words.words |annotations.wikidata |bounds.northeast.lat |bounds.northeast.lng |bounds.southwest.lat |bounds.southwest.lng |components.ISO_3166-1_alpha-2 |components.ISO_3166-1_alpha-3 |components._category |components._type |components.city |components.continent |components.country       |components.country_code |components.county |components.postcode |components.state |components.state_code |confidence |formatted                                       | geometry.lat| geometry.lng|components.municipality |components.village |query  |
|:--------------------|:--------------------|:-----------------------|:----------------------|:----------------|:----------------------|:----------------------|:----------------------|:------------------------------------------------------------------------------|:-------------------------------------------------------------------------|:-------------------------------------------------------------------------------------|:-----------------------------------|:-------------------------------------------|:-----------------------------|:--------------------------------|:----------------------------------------|:-----------------------|:--------------------------------------|:---------------------------------|:----------------------------------------|:--------------------------------|:-----------------------------|:--------------------------------|:-------------------------|:------------------------------------------|:----------------------------|:------------------------------------|:---------------------------|:---------------------------------|:----------------------------------------|:------------------------|:--------------------|:-----------------|:-----------------------------|:-----------------------------|:-----------------------------|:---------------------------------|:--------------------------|:-----------------------------|:----------------------------|:--------------------------------|:-------------------------|:----------------------------|:-------------------------|:-------------------------------|:-------------------------------|:----------------------------------|:-------------------------------|:----------------------------|:--------------------|:--------------------|:--------------------|:--------------------|:--------------------|:-----------------------------|:-----------------------------|:--------------------|:----------------|:---------------|:--------------------|:------------------------|:-----------------------|:-----------------|:-------------------|:----------------|:---------------------|:----------|:-----------------------------------------------|------------:|------------:|:-----------------------|:------------------|:------|
|44° 28' 8.65560'' N  |71° 11' 6.81360'' W  |33007                   |33                     |19TCK2618626296  |FN44jl72sn             |-7924303.11            |5508377.717            |https://www.openstreetmap.org/edit?relation=170184#map=17/44.46907/-71.18523   |https://www.openstreetmap.org/note/new#map=17/44.46907/-71.18523&layers=N |https://www.openstreetmap.org/?mlat=44.46907&mlon=-71.18523#map=17/44.46907/-71.18523 |019                                 |021                                         |840                           |001                              |MEDC                                     |1                       |US$                                    |.                                 |US$                                      |$                                |USD                           |840                              |United States Dollar      |1                                          |Cent                         |100                                  |$                           |1                                 |,                                        |<U+0001F1FA><U+0001F1F8> |drvkupke058m4sb6360c |60.36             |right                         |mph                           |1601981400                    |1601975640                        |1601979660                 |1601977680                    |1602022440                   |1602028200                       |1602024180                |1602026220                   |America/New_York          |1                               |-14400                          |-0400                              |EDT                             |strong.clean.crib            |Q821244              |44.528436            |-71.123642           |44.445057            |-71.397858           |US                            |USA                           |place                |city             |Berlin          |North America        |United States of America |us                      |Coos County       |03570               |New Hampshire    |NH                    |5          |Berlin, New Hampshire, United States of America |     44.46907|    -71.18523|NA                      |NA                 |Berlin |
|39° 45' 32.17932'' N |89° 54' 11.38860'' W |17167                   |17                     |16SBK5129805033  |EM59bs12od             |-10007974.382          |4803640.851            |https://www.openstreetmap.org/edit?relation=126290#map=17/39.75894/-89.90316   |https://www.openstreetmap.org/note/new#map=17/39.75894/-89.90316&layers=N |https://www.openstreetmap.org/?mlat=39.75894&mlon=-89.90316#map=17/39.75894/-89.90316 |019                                 |021                                         |840                           |001                              |MEDC                                     |1                       |US$                                    |.                                 |US$                                      |$                                |USD                           |840                              |United States Dollar      |1                                          |Cent                         |100                                  |$                           |1                                 |,                                        |<U+0001F1FA><U+0001F1F8> |dp044jys87qe8cu91khu |47.27             |right                         |mph                           |1601985720                    |1601980380                        |1601984160                 |1601982240                    |1602027120                   |1601946060                       |1602028740                |1601944200                   |America/Chicago           |1                               |-18000                          |-0500                              |CDT                             |scouting.forum.whispering    |Q2504681             |39.764932            |-89.893165           |39.750371            |-89.912101           |US                            |USA                           |place                |city             |Berlin          |North America        |United States of America |us                      |Sangamon County   |NA                  |Illinois         |IL                    |8          |Berlin, Illinois, United States of America      |     39.75894|    -89.90316|NA                      |NA                 |Berlin |
|41° 37' 17.35680'' N |72° 44' 44.34684'' W |09003                   |09                     |18TXM8780710206  |FN31po09md             |-8098008.927           |5076059.694            |https://www.openstreetmap.org/edit?relation=11042445#map=17/41.62149/-72.74565 |https://www.openstreetmap.org/note/new#map=17/41.62149/-72.74565&layers=N |https://www.openstreetmap.org/?mlat=41.62149&mlon=-72.74565#map=17/41.62149/-72.74565 |019                                 |021                                         |840                           |001                              |MEDC                                     |1                       |US$                                    |.                                 |US$                                      |$                                |USD                           |840                              |United States Dollar      |1                                          |Cent                         |100                                  |$                           |1                                 |,                                        |<U+0001F1FA><U+0001F1F8> |drkkb8unxrwqyhztwm4q |59.3              |right                         |mph                           |1601981700                    |1601976180                        |1601980020                 |1601978100                    |1602022920                   |1602028440                       |1602024600                |1602026520                   |America/New_York          |1                               |-14400                          |-0400                              |EDT                             |frosts.crowds.reef           |Q821199              |41.6527197           |-72.7111349          |41.554197            |-72.8402567          |US                            |USA                           |place                |city             |Berlin          |North America        |United States of America |us                      |Hartford County   |NA                  |Connecticut      |CT                    |6          |Berlin, Connecticut, United States of America   |     41.62149|    -72.74565|NA                      |NA                 |Berlin |
|38° 19' 21.41544'' N |75° 13' 3.68112'' W  |24047                   |24                     |18SVH8097141633  |FM28jh37vk             |-8373194.86            |4598602.233            |https://www.openstreetmap.org/edit?relation=133689#map=17/38.32262/-75.21769   |https://www.openstreetmap.org/note/new#map=17/38.32262/-75.21769&layers=N |https://www.openstreetmap.org/?mlat=38.32262&mlon=-75.21769#map=17/38.32262/-75.21769 |019                                 |021                                         |840                           |001                              |MEDC                                     |1                       |US$                                    |.                                 |US$                                      |$                                |USD                           |840                              |United States Dollar      |1                                          |Cent                         |100                                  |$                           |1                                 |,                                        |<U+0001F1FA><U+0001F1F8> |dqfd02kjkv3c6dwm8g5s |57.81             |right                         |mph                           |1601982180                    |1601976900                        |1601980560                 |1601978760                    |1602023640                   |1601942460                       |1602025200                |1602027060                   |America/New_York          |1                               |-14400                          |-0400                              |EDT                             |floral.evenly.shortwave      |Q614184              |38.355184            |-75.1879942          |38.308406            |-75.234794           |US                            |USA                           |place                |city             |Berlin          |North America        |United States of America |us                      |Worcester County  |NA                  |Maryland         |MD                    |7          |Berlin, Maryland, United States of America      |     38.32262|    -75.21769|NA                      |NA                 |Berlin |
|44° 12' 36.27324'' N |72° 36' 12.25764'' W |50023                   |50                     |18TXP9146797998  |FN34qf70ok             |-8082174.068           |5468204.6              |https://www.openstreetmap.org/edit?relation=8898132#map=17/44.21008/-72.60340  |https://www.openstreetmap.org/note/new#map=17/44.21008/-72.60340&layers=N |https://www.openstreetmap.org/?mlat=44.21008&mlon=-72.60340#map=17/44.21008/-72.60340 |019                                 |021                                         |840                           |001                              |MEDC                                     |1                       |US$                                    |.                                 |US$                                      |$                                |USD                           |840                              |United States Dollar      |1                                          |Cent                         |100                                  |$                           |1                                 |,                                        |<U+0001F1FA><U+0001F1F8> |dru7eb5y653rny3vp3ww |59.37             |right                         |mph                           |1601981760                    |1601976000                        |1601980020                 |1601978040                    |1602022800                   |1602028560                       |1602024540                |1602026520                   |America/New_York          |1                               |-14400                          |-0400                              |EDT                             |grooves.fearfully.classic    |Q821245              |44.2719667           |-72.5197921          |44.1547824           |-72.6836842          |US                            |USA                           |place                |city             |Berlin          |North America        |United States of America |us                      |Washington County |NA                  |Vermont          |VT                    |6          |Berlin, Vermont, United States of America       |     44.21008|    -72.60340|NA                      |NA                 |Berlin |
|39° 47' 28.41432'' N |74° 55' 44.59296'' W |34007                   |34                     |18SWK0607404588  |FM29ms89mv             |-8341064.092           |4808298.871            |https://www.openstreetmap.org/edit?relation=170680#map=17/39.79123/-74.92905   |https://www.openstreetmap.org/note/new#map=17/39.79123/-74.92905&layers=N |https://www.openstreetmap.org/?mlat=39.79123&mlon=-74.92905#map=17/39.79123/-74.92905 |019                                 |021                                         |840                           |001                              |MEDC                                     |1                       |US$                                    |.                                 |US$                                      |$                                |USD                           |840                              |United States Dollar      |1                                          |Cent                         |100                                  |$                           |1                                 |,                                        |<U+0001F1FA><U+0001F1F8> |dr4dqgy2dw0juru53e8c |57.91             |right                         |mph                           |1601982180                    |1601976780                        |1601980560                 |1601978640                    |1602023520                   |1601942460                       |1602025140                |1602027000                   |America/New_York          |1                               |-14400                          |-0400                              |EDT                             |verdict.rushes.upgrading     |Q1086827             |39.8091498           |-74.907959           |39.77601             |-74.966113           |US                            |USA                           |place                |city             |Berlin          |North America        |United States of America |us                      |Camden County     |NA                  |New Jersey       |NJ                    |7          |Berlin, New Jersey, United States of America    |     39.79123|    -74.92905|NA                      |NA                 |Berlin |
|42° 23' 2.04900'' N  |71° 37' 57.15660'' W |25027                   |25                     |19TBG8328795759  |FN42ej42cd             |-7974098.267           |5189849.26             |https://www.openstreetmap.org/edit?relation=1844156#map=17/42.38390/-71.63254  |https://www.openstreetmap.org/note/new#map=17/42.38390/-71.63254&layers=N |https://www.openstreetmap.org/?mlat=42.38390&mlon=-71.63254#map=17/42.38390/-71.63254 |019                                 |021                                         |840                           |001                              |MEDC                                     |1                       |US$                                    |.                                 |US$                                      |$                                |USD                           |840                              |United States Dollar      |1                                          |Cent                         |100                                  |$                           |1                                 |,                                        |<U+0001F1FA><U+0001F1F8> |drt11gyb0u04x1wbc76t |60.04             |right                         |mph                           |1601981460                    |1601975880                        |1601979780                 |1601977800                    |1602022620                   |1602028200                       |1602024300                |1602026280                   |America/New_York          |1                               |-14400                          |-0400                              |EDT                             |wires.examination.boom       |Q524646              |42.4182323           |-71.5801342          |42.3504652           |-71.6787662          |US                            |USA                           |place                |city             |Berlin          |North America        |United States of America |us                      |Worcester County  |01503               |Massachusetts    |MA                    |7          |Berlin, Massachusetts, United States of America |     42.38390|    -71.63254|NA                      |NA                 |Berlin |
|39° 55' 14.29068'' N |78° 57' 28.08792'' W |42111                   |42                     |17SPE7452920945  |FM09mw50bw             |-8789542.335           |4826990.633            |https://www.openstreetmap.org/edit?relation=189091#map=17/39.92064/-78.95780   |https://www.openstreetmap.org/note/new#map=17/39.92064/-78.95780&layers=N |https://www.openstreetmap.org/?mlat=39.92064&mlon=-78.95780#map=17/39.92064/-78.95780 |019                                 |021                                         |840                           |001                              |MEDC                                     |1                       |US$                                    |.                                 |US$                                      |$                                |USD                           |840                              |United States Dollar      |1                                          |Cent                         |100                                  |$                           |1                                 |,                                        |<U+0001F1FA><U+0001F1F8> |dppg572dtcgrq3gysfyq |55.17             |right                         |mph                           |1601983140                    |1601977740                        |1601981520                 |1601979660                    |1602024480                   |1601943420                       |1602026100                |1602027960                   |America/New_York          |1                               |-14400                          |-0400                              |EDT                             |rangers.chopsticks.crumbs    |Q1130950             |39.92738             |-78.937285           |39.914422            |-78.965592           |US                            |USA                           |place                |city             |Berlin          |North America        |United States of America |us                      |Somerset County   |NA                  |Pennsylvania     |PA                    |8          |Berlin, Pennsylvania, United States of America  |     39.92064|    -78.95780|NA                      |NA                 |Berlin |
|42° 41' 35.28636'' N |73° 22' 19.39764'' W |36083                   |36                     |18TXN3335128023  |FN32hq56ii             |-8167739.79            |5236398.071            |https://www.openstreetmap.org/edit?node=158915747#map=17/42.69314/-73.37205    |https://www.openstreetmap.org/note/new#map=17/42.69314/-73.37205&layers=N |https://www.openstreetmap.org/?mlat=42.69314&mlon=-73.37205#map=17/42.69314/-73.37205 |019                                 |021                                         |840                           |001                              |MEDC                                     |1                       |US$                                    |.                                 |US$                                      |$                                |USD                           |840                              |United States Dollar      |1                                          |Cent                         |100                                  |$                           |1                                 |,                                        |<U+0001F1FA><U+0001F1F8> |dreffkh1e1nwb7qznzmj |58.85             |right                         |mph                           |1601981880                    |1601976240                        |1601980200                 |1601978220                    |1602023040                   |1602028620                       |1602024720                |1602026700                   |America/New_York          |1                               |-14400                          |-0400                              |EDT                             |cartons.eliminates.uses      |NA                   |42.7131351           |-73.3520549          |42.6731351           |-73.3920549          |US                            |USA                           |place                |village          |NA              |North America        |United States of America |us                      |Rensselaer County |12022               |New York         |NY                    |7          |Berlin, NY 12022, United States of America      |     42.69314|    -73.37205|Town of Berlin          |Berlin             |Berlin |
|40° 33' 40.24080'' N |81° 47' 39.60708'' W |39075                   |39                     |17TME3275390348  |EN90cn44qq             |-9105303.755           |4920038.592            |https://www.openstreetmap.org/edit?node=153968558#map=17/40.56118/-81.79434    |https://www.openstreetmap.org/note/new#map=17/40.56118/-81.79434&layers=N |https://www.openstreetmap.org/?mlat=40.56118&mlon=-81.79434#map=17/40.56118/-81.79434 |019                                 |021                                         |840                           |001                              |MEDC                                     |1                       |US$                                    |.                                 |US$                                      |$                                |USD                           |840                              |United States Dollar      |1                                          |Cent                         |100                                  |$                           |1                                 |,                                        |<U+0001F1FA><U+0001F1F8> |dpjydxzjvze56k2d7968 |53.12             |right                         |mph                           |1601983800                    |1601978400                        |1601982180                 |1601980320                    |1602025140                   |1601944140                       |1602026760                |1602028680                   |America/New_York          |1                               |-14400                          |-0400                              |EDT                             |gained.adjusts.scrap         |NA                   |40.581178            |-81.7743353          |40.541178            |-81.8143353          |US                            |USA                           |place                |village          |NA              |North America        |United States of America |us                      |Holmes            |44610               |Ohio             |OH                    |7          |Berlin, OH 44610, United States of America      |     40.56118|    -81.79434|NA                      |Berlin             |Berlin |

* `countrycode`: Restricts the results to the given country. The country code is a two letter code as defined by the ISO 3166-1 Alpha 2 standard. E.g. "GB" for the United Kingdom, "FR" for France, "US" for United States. See example below.


```r
results3 <- opencage_forward(placename = "Berlin", country = "DE")
results3$results %>% knitr::kable()
```



|annotations.DMS.lat  |annotations.DMS.lng  |annotations.MGRS |annotations.Maidenhead |annotations.Mercator.x |annotations.Mercator.y |annotations.OSM.edit_url                                                    |annotations.OSM.note_url                                                 |annotations.OSM.url                                                                 |annotations.UN_M49.regions.DE |annotations.UN_M49.regions.EUROPE |annotations.UN_M49.regions.WESTERN_EUROPE |annotations.UN_M49.regions.WORLD |annotations.UN_M49.statistical_groupings |annotations.callingcode |annotations.currency.decimal_mark |annotations.currency.html_entity |annotations.currency.iso_code |annotations.currency.iso_numeric |annotations.currency.name |annotations.currency.smallest_denomination |annotations.currency.subunit |annotations.currency.subunit_to_unit |annotations.currency.symbol |annotations.currency.symbol_first |annotations.currency.thousands_separator |annotations.flag         |annotations.geohash  |annotations.qibla |annotations.roadinfo.drive_on |annotations.roadinfo.speed_in |annotations.sun.rise.apparent |annotations.sun.rise.astronomical |annotations.sun.rise.civil |annotations.sun.rise.nautical |annotations.sun.set.apparent |annotations.sun.set.astronomical |annotations.sun.set.civil |annotations.sun.set.nautical |annotations.timezone.name |annotations.timezone.now_in_dst |annotations.timezone.offset_sec |annotations.timezone.offset_string |annotations.timezone.short_name |annotations.what3words.words |annotations.wikidata |bounds.northeast.lat |bounds.northeast.lng |bounds.southwest.lat |bounds.southwest.lng |components.ISO_3166-1_alpha-2 |components.ISO_3166-1_alpha-3 |components._category |components._type |components.city |components.continent |components.country |components.country_code |components.political_union |components.state       |components.state_code |confidence |formatted                                                                   | geometry.lat| geometry.lng|annotations.roadinfo.road |components.borough         |components.postcode |components.road  |components.suburb                    |components.tourism |components.county   |components.municipality |components.village |components.hamlet |components.neighbourhood |components.shop |components.historic |components.city_district |components.house_number |components.quarter              |components.town |query  |
|:--------------------|:--------------------|:----------------|:----------------------|:----------------------|:----------------------|:---------------------------------------------------------------------------|:------------------------------------------------------------------------|:-----------------------------------------------------------------------------------|:-----------------------------|:---------------------------------|:-----------------------------------------|:--------------------------------|:----------------------------------------|:-----------------------|:---------------------------------|:--------------------------------|:-----------------------------|:--------------------------------|:-------------------------|:------------------------------------------|:----------------------------|:------------------------------------|:---------------------------|:---------------------------------|:----------------------------------------|:------------------------|:--------------------|:-----------------|:-----------------------------|:-----------------------------|:-----------------------------|:---------------------------------|:--------------------------|:-----------------------------|:----------------------------|:--------------------------------|:-------------------------|:----------------------------|:-------------------------|:-------------------------------|:-------------------------------|:----------------------------------|:-------------------------------|:----------------------------|:--------------------|:--------------------|:--------------------|:--------------------|:--------------------|:-----------------------------|:-----------------------------|:--------------------|:----------------|:---------------|:--------------------|:------------------|:-----------------------|:--------------------------|:----------------------|:---------------------|:----------|:---------------------------------------------------------------------------|------------:|------------:|:-------------------------|:--------------------------|:-------------------|:----------------|:------------------------------------|:------------------|:-------------------|:-----------------------|:------------------|:-----------------|:------------------------|:---------------|:-------------------|:------------------------|:-----------------------|:-------------------------------|:---------------|:------|
|52° 31' 1.33140'' N  |13° 23' 19.89564'' E |33UUU9067619766  |JO62qm64pc             |1490441.066            |6860227.862            |https://www.openstreetmap.org/edit?relation=62422#map=16/52.51704/13.38886  |https://www.openstreetmap.org/note/new#map=16/52.51704/13.38886&layers=N |https://www.openstreetmap.org/?mlat=52.51704&mlon=13.38886#map=16/52.51704/13.38886 |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u33db8mmzj1t355u0c0j |136.66            |right                         |km/h                          |1601961480                    |1601954640                        |1601959440                 |1601957040                    |1602001800                   |1602008640                       |1602003840                |1602006240                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |third.gurgled.such           |Q64                  |52.6755087           |13.7611609           |52.3382448           |13.088345            |DE                            |DEU                           |place                |city             |Berlin          |Europe               |Germany            |de                      |European Union             |Berlin                 |BE                    |2          |Berlin, Germany                                                             |     52.51704|    13.388860|NA                        |NA                         |NA                  |NA               |NA                                   |NA                 |NA                  |NA                      |NA                 |NA                |NA                       |NA              |NA                  |NA                       |NA                      |NA                              |NA              |Berlin |
|52° 30' 12.24072'' N |13° 20' 19.09428'' E |33UUU8723418327  |JO62qm00pt             |1484850.312            |6857739.929            |https://www.openstreetmap.org/edit?node=313826576#map=16/52.50340/13.33864  |https://www.openstreetmap.org/note/new#map=16/52.50340/13.33864&layers=N |https://www.openstreetmap.org/?mlat=52.50340&mlon=13.33864#map=16/52.50340/13.33864 |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u336xtbykz0vehy92f44 |136.58            |right                         |km/h                          |1601961480                    |1601954640                        |1601959440                 |1601957040                    |1602001860                   |1602008640                       |1602003840                |1602006240                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |latched.viewers.robot        |Q4783389             |52.5034502           |13.3386873           |52.5033502           |13.3385873           |DE                            |DEU                           |unknown              |borough          |Berlin          |Europe               |Germany            |de                      |European Union             |Berlin                 |BE                    |9          |Charlottenburg-Wilmersdorf, Berlin, Tauentzienstraße, 10789 Berlin, Germany |     52.50340|    13.338637|Tauentzienstraße          |Charlottenburg-Wilmersdorf |10789               |Tauentzienstraße |Charlottenburg                       |Berlin             |NA                  |NA                      |NA                 |NA                |NA                       |NA              |NA                  |NA                       |NA                      |NA                              |NA              |Berlin |
|54° 2' 10.89780'' N  |10° 26' 46.07268'' E |32UNE9470788534  |JO54fa38mr             |1162858.017            |7142435.831            |https://www.openstreetmap.org/edit?node=50798110#map=16/54.03636/10.44613   |https://www.openstreetmap.org/note/new#map=16/54.03636/10.44613&layers=N |https://www.openstreetmap.org/?mlat=54.03636&mlon=10.44613#map=16/54.03636/10.44613 |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u1x7mtn8se8n18vzuczv |134.07            |right                         |km/h                          |1601962260                    |1601955180                        |1601960160                 |1601957700                    |1602002460                   |1602009480                       |1602004560                |1602007020                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |jungle.scaled.quantity       |Q12053136            |54.0563605           |10.4661313           |54.0163605           |10.4261313           |DE                            |DEU                           |place                |village          |NA              |Europe               |Germany            |de                      |European Union             |Schleswig-Holstein     |SH                    |7          |23823 Berlin, Germany                                                       |     54.03636|    10.446131|NA                        |NA                         |23823               |NA               |NA                                   |NA                 |Segeberg            |Trave-Land              |Berlin             |NA                |NA                       |NA              |NA                  |NA                       |NA                      |NA                              |NA              |Berlin |
|54° 24' 18.42840'' N |9° 25' 55.18776'' E  |32UNF2804128682  |JO44rj17uf             |1049965.059            |7212486.314            |https://www.openstreetmap.org/edit?way=68276512#map=16/54.40512/9.43200     |https://www.openstreetmap.org/note/new#map=16/54.40512/9.43200&layers=N  |https://www.openstreetmap.org/?mlat=54.40512&mlon=9.43200#map=16/54.40512/9.43200   |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u1wtw8hhv3q2jjmfesu3 |133.07            |right                         |km/h                          |1601962500                    |1601955360                        |1601960400                 |1601957880                    |1602002640                   |1602009780                       |1602004800                |1602007260                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |makeups.propelled.panther    |NA                   |54.4069751           |9.4342708            |54.4029778           |9.4299614            |DE                            |DEU                           |road                 |road             |NA              |Europe               |Germany            |de                      |European Union             |Schleswig-Holstein     |SH                    |9          |Berlin, 24848 Klein Bennebek, Germany                                       |     54.40512|     9.431997|Berlin                    |NA                         |24848               |Berlin           |NA                                   |NA                 |Schleswig-Flensburg |Kropp-Stapelholm        |Klein Bennebek     |Potsdam           |NA                       |NA              |NA                  |NA                       |NA                      |NA                              |NA              |Berlin |
|52° 25' 7.43664'' N  |13° 11' 47.05872'' E |33UUU7734509142  |JO62ok30nl             |1469017.107            |6842309.679            |https://www.openstreetmap.org/edit?node=1069490670#map=16/52.41873/13.19641 |https://www.openstreetmap.org/note/new#map=16/52.41873/13.19641&layers=N |https://www.openstreetmap.org/?mlat=52.41873&mlon=13.19641#map=16/52.41873/13.19641 |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u336hq934xbyt1e6fspy |136.31            |right                         |km/h                          |1601961480                    |1601954700                        |1601959440                 |1601957100                    |1602001860                   |1602008640                       |1602003900                |1602006240                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |vibes.outpost.stocky         |NA                   |52.4187824           |13.1964552           |52.4186824           |13.1963552           |DE                            |DEU                           |unknown              |borough          |Berlin          |Europe               |Germany            |de                      |European Union             |Berlin                 |BE                    |9          |Steglitz-Zehlendorf, Berlin, A 115, 14109 Berlin, Germany                   |     52.41873|    13.196405|A 115                     |Steglitz-Zehlendorf        |14109               |A 115            |Nikolassee                           |Berlin             |NA                  |NA                      |NA                 |NA                |NA                       |NA              |NA                  |NA                       |NA                      |NA                              |NA              |Berlin |
|52° 31' 15.16908'' N |13° 24' 38.79864'' E |33UUU9217320161  |JO62qm95ha             |1492880.911            |6860929.301            |https://www.openstreetmap.org/edit?node=4389014593#map=16/52.52088/13.41078 |https://www.openstreetmap.org/note/new#map=16/52.52088/13.41078&layers=N |https://www.openstreetmap.org/?mlat=52.52088&mlon=13.41078#map=16/52.52088/13.41078 |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u33dc1jkmc8qt030p2q8 |136.69            |right                         |km/h                          |1601961480                    |1601954640                        |1601959440                 |1601957040                    |1602001800                   |1602008640                       |1602003840                |1602006240                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |workouts.pastime.under       |NA                   |52.5209303           |13.4108274           |52.5208303           |13.4107274           |DE                            |DEU                           |unknown              |borough          |Berlin          |Europe               |Germany            |de                      |European Union             |Berlin                 |BE                    |9          |Mitte, Berlin, Gontardstraße, 10178 Berlin, Germany                         |     52.52088|    13.410777|Gontardstraße             |Mitte                      |10178               |Gontardstraße    |Mitte                                |NA                 |NA                  |NA                      |NA                 |NA                |Spandauer Vorstadt       |Berlin          |NA                  |NA                       |NA                      |NA                              |NA              |Berlin |
|52° 22' 12.67680'' N |9° 45' 10.62252'' E  |32UND5126202479  |JO42vi08iu             |1085693.506            |6833476.151            |https://www.openstreetmap.org/edit?node=320881943#map=16/52.37019/9.75295   |https://www.openstreetmap.org/note/new#map=16/52.37019/9.75295&layers=N  |https://www.openstreetmap.org/?mlat=52.37019&mlon=9.75295#map=16/52.37019/9.75295   |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u1qcvvtyknx5um9fq9f9 |131.66            |right                         |km/h                          |1601962320                    |1601955540                        |1601960280                 |1601957940                    |1602002700                   |1602009480                       |1602004740                |1602007080                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |army.outdoors.hitters        |NA                   |52.370238            |9.7530007            |52.370138            |9.7529007            |DE                            |DEU                           |unknown              |historic         |Hanover         |Europe               |Germany            |de                      |European Union             |Lower Saxony           |NI                    |9          |Berliner Allee, 30175 Hanover, Germany                                      |     52.37019|     9.752951|Berliner Allee            |NA                         |30175               |Berliner Allee   |South-City-Bult                      |NA                 |Region Hannover     |NA                      |NA                 |NA                |NA                       |NA              |Berlin              |NA                       |NA                      |NA                              |NA              |Berlin |
|53° 51' 4.53384'' N  |10° 40' 56.93196'' E |32UPE1067368285  |JO53iu14vh             |1189168.356            |7107508.609            |https://www.openstreetmap.org/edit?node=1630863689#map=16/53.85126/10.68248 |https://www.openstreetmap.org/note/new#map=16/53.85126/10.68248&layers=N |https://www.openstreetmap.org/?mlat=53.85126&mlon=10.68248#map=16/53.85126/10.68248 |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u1xd756drf74zwdx76by |134.21            |right                         |km/h                          |1601962200                    |1601955120                        |1601960100                 |1601957640                    |1602002400                   |1602009420                       |1602004500                |1602006900                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |chase.pencils.themes         |NA                   |53.8513094           |10.6825311           |53.8512094           |10.6824311           |DE                            |DEU                           |unknown              |historic         |Lübeck          |Europe               |Germany            |de                      |European Union             |Schleswig-Holstein     |SH                    |9          |Berliner Platz, 23560 Lübeck, Germany                                       |     53.85126|    10.682481|Berliner Platz            |NA                         |23560               |Berliner Platz   |Hüxtertor / Mühlentor / Gärtnergasse |NA                 |NA                  |NA                      |NA                 |NA                |NA                       |NA              |Berlin              |Sankt Jürgen             |NA                      |NA                              |NA              |Berlin |
|52° 1' 36.20388'' N  |8° 32' 4.49556'' E   |32UMC6806764112  |JO42ga46dj             |950065.334             |6771253.541            |https://www.openstreetmap.org/edit?node=4320672889#map=16/52.02672/8.53458  |https://www.openstreetmap.org/note/new#map=16/52.02672/8.53458&layers=N  |https://www.openstreetmap.org/?mlat=52.02672&mlon=8.53458#map=16/52.02672/8.53458   |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u1npfpntwhjtjju75d94 |129.77            |right                         |km/h                          |1601962620                    |1601955840                        |1601960580                 |1601958240                    |1602003000                   |1602009720                       |1602005040                |1602007380                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |upstairs.cursing.gives       |NA                   |52.0267733           |8.5346321            |52.0266733           |8.5345321            |DE                            |DEU                           |commerce             |shop             |Bielefeld       |Europe               |Germany            |de                      |European Union             |North Rhine-Westphalia |NW                    |9          |Berlin, Herforder Straße 33, 33602 Bielefeld, Germany                       |     52.02672|     8.534582|Herforder Straße          |NA                         |33602               |Herforder Straße |Mitte                                |NA                 |NA                  |NA                      |NA                 |NA                |NA                       |Berlin          |NA                  |NA                       |33                      |NA                              |NA              |Berlin |
|47° 59' 4.71444'' N  |10° 11' 11.83056'' E |32TNU8854215274  |JN57cx26jh             |1133969.307            |6072538.283            |https://www.openstreetmap.org/edit?node=4880207121#map=16/47.98464/10.18662 |https://www.openstreetmap.org/note/new#map=16/47.98464/10.18662&layers=N |https://www.openstreetmap.org/?mlat=47.98464&mlon=10.18662#map=16/47.98464/10.18662 |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u0x0zz3dv3y07kdqqkqc |127.77            |right                         |km/h                          |1601962020                    |1601955840                        |1601960160                 |1601958000                    |1602002820                   |1602009000                       |1602004680                |1602006780                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |tarred.cheater.happier       |NA                   |47.9846929           |10.1866696           |47.9845929           |10.1865696           |DE                            |DEU                           |unknown              |historic         |NA              |Europe               |Germany            |de                      |European Union             |Bavaria                |BY                    |9          |Berlin, 3, 87700 Memmingen, Germany                                         |     47.98464|    10.186620|3                         |NA                         |87700               |3                |Neubruch                             |NA                 |NA                  |NA                      |NA                 |NA                |NA                       |NA              |Berlin              |NA                       |NA                      |Gewerbegebiet Schlachthofstraße |Memmingen       |Berlin |

* `language`: an IETF format language code (such as "es" for Spanish or "pt-BR" for Brazilian Portuguese). If no language is explicitly specified, we will look for an HTTP Accept-Language header like those sent by a brower and use the first language specified and if none are specified "en" (English) will be assumed. See example below.


```r
results3$results %>% knitr::kable()
```



|annotations.DMS.lat  |annotations.DMS.lng  |annotations.MGRS |annotations.Maidenhead |annotations.Mercator.x |annotations.Mercator.y |annotations.OSM.edit_url                                                    |annotations.OSM.note_url                                                 |annotations.OSM.url                                                                 |annotations.UN_M49.regions.DE |annotations.UN_M49.regions.EUROPE |annotations.UN_M49.regions.WESTERN_EUROPE |annotations.UN_M49.regions.WORLD |annotations.UN_M49.statistical_groupings |annotations.callingcode |annotations.currency.decimal_mark |annotations.currency.html_entity |annotations.currency.iso_code |annotations.currency.iso_numeric |annotations.currency.name |annotations.currency.smallest_denomination |annotations.currency.subunit |annotations.currency.subunit_to_unit |annotations.currency.symbol |annotations.currency.symbol_first |annotations.currency.thousands_separator |annotations.flag         |annotations.geohash  |annotations.qibla |annotations.roadinfo.drive_on |annotations.roadinfo.speed_in |annotations.sun.rise.apparent |annotations.sun.rise.astronomical |annotations.sun.rise.civil |annotations.sun.rise.nautical |annotations.sun.set.apparent |annotations.sun.set.astronomical |annotations.sun.set.civil |annotations.sun.set.nautical |annotations.timezone.name |annotations.timezone.now_in_dst |annotations.timezone.offset_sec |annotations.timezone.offset_string |annotations.timezone.short_name |annotations.what3words.words |annotations.wikidata |bounds.northeast.lat |bounds.northeast.lng |bounds.southwest.lat |bounds.southwest.lng |components.ISO_3166-1_alpha-2 |components.ISO_3166-1_alpha-3 |components._category |components._type |components.city |components.continent |components.country |components.country_code |components.political_union |components.state       |components.state_code |confidence |formatted                                                                   | geometry.lat| geometry.lng|annotations.roadinfo.road |components.borough         |components.postcode |components.road  |components.suburb                    |components.tourism |components.county   |components.municipality |components.village |components.hamlet |components.neighbourhood |components.shop |components.historic |components.city_district |components.house_number |components.quarter              |components.town |query  |
|:--------------------|:--------------------|:----------------|:----------------------|:----------------------|:----------------------|:---------------------------------------------------------------------------|:------------------------------------------------------------------------|:-----------------------------------------------------------------------------------|:-----------------------------|:---------------------------------|:-----------------------------------------|:--------------------------------|:----------------------------------------|:-----------------------|:---------------------------------|:--------------------------------|:-----------------------------|:--------------------------------|:-------------------------|:------------------------------------------|:----------------------------|:------------------------------------|:---------------------------|:---------------------------------|:----------------------------------------|:------------------------|:--------------------|:-----------------|:-----------------------------|:-----------------------------|:-----------------------------|:---------------------------------|:--------------------------|:-----------------------------|:----------------------------|:--------------------------------|:-------------------------|:----------------------------|:-------------------------|:-------------------------------|:-------------------------------|:----------------------------------|:-------------------------------|:----------------------------|:--------------------|:--------------------|:--------------------|:--------------------|:--------------------|:-----------------------------|:-----------------------------|:--------------------|:----------------|:---------------|:--------------------|:------------------|:-----------------------|:--------------------------|:----------------------|:---------------------|:----------|:---------------------------------------------------------------------------|------------:|------------:|:-------------------------|:--------------------------|:-------------------|:----------------|:------------------------------------|:------------------|:-------------------|:-----------------------|:------------------|:-----------------|:------------------------|:---------------|:-------------------|:------------------------|:-----------------------|:-------------------------------|:---------------|:------|
|52° 31' 1.33140'' N  |13° 23' 19.89564'' E |33UUU9067619766  |JO62qm64pc             |1490441.066            |6860227.862            |https://www.openstreetmap.org/edit?relation=62422#map=16/52.51704/13.38886  |https://www.openstreetmap.org/note/new#map=16/52.51704/13.38886&layers=N |https://www.openstreetmap.org/?mlat=52.51704&mlon=13.38886#map=16/52.51704/13.38886 |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u33db8mmzj1t355u0c0j |136.66            |right                         |km/h                          |1601961480                    |1601954640                        |1601959440                 |1601957040                    |1602001800                   |1602008640                       |1602003840                |1602006240                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |third.gurgled.such           |Q64                  |52.6755087           |13.7611609           |52.3382448           |13.088345            |DE                            |DEU                           |place                |city             |Berlin          |Europe               |Germany            |de                      |European Union             |Berlin                 |BE                    |2          |Berlin, Germany                                                             |     52.51704|    13.388860|NA                        |NA                         |NA                  |NA               |NA                                   |NA                 |NA                  |NA                      |NA                 |NA                |NA                       |NA              |NA                  |NA                       |NA                      |NA                              |NA              |Berlin |
|52° 30' 12.24072'' N |13° 20' 19.09428'' E |33UUU8723418327  |JO62qm00pt             |1484850.312            |6857739.929            |https://www.openstreetmap.org/edit?node=313826576#map=16/52.50340/13.33864  |https://www.openstreetmap.org/note/new#map=16/52.50340/13.33864&layers=N |https://www.openstreetmap.org/?mlat=52.50340&mlon=13.33864#map=16/52.50340/13.33864 |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u336xtbykz0vehy92f44 |136.58            |right                         |km/h                          |1601961480                    |1601954640                        |1601959440                 |1601957040                    |1602001860                   |1602008640                       |1602003840                |1602006240                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |latched.viewers.robot        |Q4783389             |52.5034502           |13.3386873           |52.5033502           |13.3385873           |DE                            |DEU                           |unknown              |borough          |Berlin          |Europe               |Germany            |de                      |European Union             |Berlin                 |BE                    |9          |Charlottenburg-Wilmersdorf, Berlin, Tauentzienstraße, 10789 Berlin, Germany |     52.50340|    13.338637|Tauentzienstraße          |Charlottenburg-Wilmersdorf |10789               |Tauentzienstraße |Charlottenburg                       |Berlin             |NA                  |NA                      |NA                 |NA                |NA                       |NA              |NA                  |NA                       |NA                      |NA                              |NA              |Berlin |
|54° 2' 10.89780'' N  |10° 26' 46.07268'' E |32UNE9470788534  |JO54fa38mr             |1162858.017            |7142435.831            |https://www.openstreetmap.org/edit?node=50798110#map=16/54.03636/10.44613   |https://www.openstreetmap.org/note/new#map=16/54.03636/10.44613&layers=N |https://www.openstreetmap.org/?mlat=54.03636&mlon=10.44613#map=16/54.03636/10.44613 |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u1x7mtn8se8n18vzuczv |134.07            |right                         |km/h                          |1601962260                    |1601955180                        |1601960160                 |1601957700                    |1602002460                   |1602009480                       |1602004560                |1602007020                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |jungle.scaled.quantity       |Q12053136            |54.0563605           |10.4661313           |54.0163605           |10.4261313           |DE                            |DEU                           |place                |village          |NA              |Europe               |Germany            |de                      |European Union             |Schleswig-Holstein     |SH                    |7          |23823 Berlin, Germany                                                       |     54.03636|    10.446131|NA                        |NA                         |23823               |NA               |NA                                   |NA                 |Segeberg            |Trave-Land              |Berlin             |NA                |NA                       |NA              |NA                  |NA                       |NA                      |NA                              |NA              |Berlin |
|54° 24' 18.42840'' N |9° 25' 55.18776'' E  |32UNF2804128682  |JO44rj17uf             |1049965.059            |7212486.314            |https://www.openstreetmap.org/edit?way=68276512#map=16/54.40512/9.43200     |https://www.openstreetmap.org/note/new#map=16/54.40512/9.43200&layers=N  |https://www.openstreetmap.org/?mlat=54.40512&mlon=9.43200#map=16/54.40512/9.43200   |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u1wtw8hhv3q2jjmfesu3 |133.07            |right                         |km/h                          |1601962500                    |1601955360                        |1601960400                 |1601957880                    |1602002640                   |1602009780                       |1602004800                |1602007260                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |makeups.propelled.panther    |NA                   |54.4069751           |9.4342708            |54.4029778           |9.4299614            |DE                            |DEU                           |road                 |road             |NA              |Europe               |Germany            |de                      |European Union             |Schleswig-Holstein     |SH                    |9          |Berlin, 24848 Klein Bennebek, Germany                                       |     54.40512|     9.431997|Berlin                    |NA                         |24848               |Berlin           |NA                                   |NA                 |Schleswig-Flensburg |Kropp-Stapelholm        |Klein Bennebek     |Potsdam           |NA                       |NA              |NA                  |NA                       |NA                      |NA                              |NA              |Berlin |
|52° 25' 7.43664'' N  |13° 11' 47.05872'' E |33UUU7734509142  |JO62ok30nl             |1469017.107            |6842309.679            |https://www.openstreetmap.org/edit?node=1069490670#map=16/52.41873/13.19641 |https://www.openstreetmap.org/note/new#map=16/52.41873/13.19641&layers=N |https://www.openstreetmap.org/?mlat=52.41873&mlon=13.19641#map=16/52.41873/13.19641 |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u336hq934xbyt1e6fspy |136.31            |right                         |km/h                          |1601961480                    |1601954700                        |1601959440                 |1601957100                    |1602001860                   |1602008640                       |1602003900                |1602006240                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |vibes.outpost.stocky         |NA                   |52.4187824           |13.1964552           |52.4186824           |13.1963552           |DE                            |DEU                           |unknown              |borough          |Berlin          |Europe               |Germany            |de                      |European Union             |Berlin                 |BE                    |9          |Steglitz-Zehlendorf, Berlin, A 115, 14109 Berlin, Germany                   |     52.41873|    13.196405|A 115                     |Steglitz-Zehlendorf        |14109               |A 115            |Nikolassee                           |Berlin             |NA                  |NA                      |NA                 |NA                |NA                       |NA              |NA                  |NA                       |NA                      |NA                              |NA              |Berlin |
|52° 31' 15.16908'' N |13° 24' 38.79864'' E |33UUU9217320161  |JO62qm95ha             |1492880.911            |6860929.301            |https://www.openstreetmap.org/edit?node=4389014593#map=16/52.52088/13.41078 |https://www.openstreetmap.org/note/new#map=16/52.52088/13.41078&layers=N |https://www.openstreetmap.org/?mlat=52.52088&mlon=13.41078#map=16/52.52088/13.41078 |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u33dc1jkmc8qt030p2q8 |136.69            |right                         |km/h                          |1601961480                    |1601954640                        |1601959440                 |1601957040                    |1602001800                   |1602008640                       |1602003840                |1602006240                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |workouts.pastime.under       |NA                   |52.5209303           |13.4108274           |52.5208303           |13.4107274           |DE                            |DEU                           |unknown              |borough          |Berlin          |Europe               |Germany            |de                      |European Union             |Berlin                 |BE                    |9          |Mitte, Berlin, Gontardstraße, 10178 Berlin, Germany                         |     52.52088|    13.410777|Gontardstraße             |Mitte                      |10178               |Gontardstraße    |Mitte                                |NA                 |NA                  |NA                      |NA                 |NA                |Spandauer Vorstadt       |Berlin          |NA                  |NA                       |NA                      |NA                              |NA              |Berlin |
|52° 22' 12.67680'' N |9° 45' 10.62252'' E  |32UND5126202479  |JO42vi08iu             |1085693.506            |6833476.151            |https://www.openstreetmap.org/edit?node=320881943#map=16/52.37019/9.75295   |https://www.openstreetmap.org/note/new#map=16/52.37019/9.75295&layers=N  |https://www.openstreetmap.org/?mlat=52.37019&mlon=9.75295#map=16/52.37019/9.75295   |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u1qcvvtyknx5um9fq9f9 |131.66            |right                         |km/h                          |1601962320                    |1601955540                        |1601960280                 |1601957940                    |1602002700                   |1602009480                       |1602004740                |1602007080                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |army.outdoors.hitters        |NA                   |52.370238            |9.7530007            |52.370138            |9.7529007            |DE                            |DEU                           |unknown              |historic         |Hanover         |Europe               |Germany            |de                      |European Union             |Lower Saxony           |NI                    |9          |Berliner Allee, 30175 Hanover, Germany                                      |     52.37019|     9.752951|Berliner Allee            |NA                         |30175               |Berliner Allee   |South-City-Bult                      |NA                 |Region Hannover     |NA                      |NA                 |NA                |NA                       |NA              |Berlin              |NA                       |NA                      |NA                              |NA              |Berlin |
|53° 51' 4.53384'' N  |10° 40' 56.93196'' E |32UPE1067368285  |JO53iu14vh             |1189168.356            |7107508.609            |https://www.openstreetmap.org/edit?node=1630863689#map=16/53.85126/10.68248 |https://www.openstreetmap.org/note/new#map=16/53.85126/10.68248&layers=N |https://www.openstreetmap.org/?mlat=53.85126&mlon=10.68248#map=16/53.85126/10.68248 |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u1xd756drf74zwdx76by |134.21            |right                         |km/h                          |1601962200                    |1601955120                        |1601960100                 |1601957640                    |1602002400                   |1602009420                       |1602004500                |1602006900                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |chase.pencils.themes         |NA                   |53.8513094           |10.6825311           |53.8512094           |10.6824311           |DE                            |DEU                           |unknown              |historic         |Lübeck          |Europe               |Germany            |de                      |European Union             |Schleswig-Holstein     |SH                    |9          |Berliner Platz, 23560 Lübeck, Germany                                       |     53.85126|    10.682481|Berliner Platz            |NA                         |23560               |Berliner Platz   |Hüxtertor / Mühlentor / Gärtnergasse |NA                 |NA                  |NA                      |NA                 |NA                |NA                       |NA              |Berlin              |Sankt Jürgen             |NA                      |NA                              |NA              |Berlin |
|52° 1' 36.20388'' N  |8° 32' 4.49556'' E   |32UMC6806764112  |JO42ga46dj             |950065.334             |6771253.541            |https://www.openstreetmap.org/edit?node=4320672889#map=16/52.02672/8.53458  |https://www.openstreetmap.org/note/new#map=16/52.02672/8.53458&layers=N  |https://www.openstreetmap.org/?mlat=52.02672&mlon=8.53458#map=16/52.02672/8.53458   |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u1npfpntwhjtjju75d94 |129.77            |right                         |km/h                          |1601962620                    |1601955840                        |1601960580                 |1601958240                    |1602003000                   |1602009720                       |1602005040                |1602007380                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |upstairs.cursing.gives       |NA                   |52.0267733           |8.5346321            |52.0266733           |8.5345321            |DE                            |DEU                           |commerce             |shop             |Bielefeld       |Europe               |Germany            |de                      |European Union             |North Rhine-Westphalia |NW                    |9          |Berlin, Herforder Straße 33, 33602 Bielefeld, Germany                       |     52.02672|     8.534582|Herforder Straße          |NA                         |33602               |Herforder Straße |Mitte                                |NA                 |NA                  |NA                      |NA                 |NA                |NA                       |Berlin          |NA                  |NA                       |33                      |NA                              |NA              |Berlin |
|47° 59' 4.71444'' N  |10° 11' 11.83056'' E |32TNU8854215274  |JN57cx26jh             |1133969.307            |6072538.283            |https://www.openstreetmap.org/edit?node=4880207121#map=16/47.98464/10.18662 |https://www.openstreetmap.org/note/new#map=16/47.98464/10.18662&layers=N |https://www.openstreetmap.org/?mlat=47.98464&mlon=10.18662#map=16/47.98464/10.18662 |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u0x0zz3dv3y07kdqqkqc |127.77            |right                         |km/h                          |1601962020                    |1601955840                        |1601960160                 |1601958000                    |1602002820                   |1602009000                       |1602004680                |1602006780                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |tarred.cheater.happier       |NA                   |47.9846929           |10.1866696           |47.9845929           |10.1865696           |DE                            |DEU                           |unknown              |historic         |NA              |Europe               |Germany            |de                      |European Union             |Bavaria                |BY                    |9          |Berlin, 3, 87700 Memmingen, Germany                                         |     47.98464|    10.186620|3                         |NA                         |87700               |3                |Neubruch                             |NA                 |NA                  |NA                      |NA                 |NA                |NA                       |NA              |Berlin              |NA                       |NA                      |Gewerbegebiet Schlachthofstraße |Memmingen       |Berlin |

```r
results4 <- opencage_forward(placename = "Berlin", country = "DE", language = "de")
results4$results %>% knitr::kable()
```



|annotations.DMS.lat  |annotations.DMS.lng  |annotations.MGRS |annotations.Maidenhead |annotations.Mercator.x |annotations.Mercator.y |annotations.OSM.edit_url                                                    |annotations.OSM.note_url                                                 |annotations.OSM.url                                                                 |annotations.UN_M49.regions.DE |annotations.UN_M49.regions.EUROPE |annotations.UN_M49.regions.WESTERN_EUROPE |annotations.UN_M49.regions.WORLD |annotations.UN_M49.statistical_groupings |annotations.callingcode |annotations.currency.decimal_mark |annotations.currency.html_entity |annotations.currency.iso_code |annotations.currency.iso_numeric |annotations.currency.name |annotations.currency.smallest_denomination |annotations.currency.subunit |annotations.currency.subunit_to_unit |annotations.currency.symbol |annotations.currency.symbol_first |annotations.currency.thousands_separator |annotations.flag         |annotations.geohash  |annotations.qibla |annotations.roadinfo.drive_on |annotations.roadinfo.speed_in |annotations.sun.rise.apparent |annotations.sun.rise.astronomical |annotations.sun.rise.civil |annotations.sun.rise.nautical |annotations.sun.set.apparent |annotations.sun.set.astronomical |annotations.sun.set.civil |annotations.sun.set.nautical |annotations.timezone.name |annotations.timezone.now_in_dst |annotations.timezone.offset_sec |annotations.timezone.offset_string |annotations.timezone.short_name |annotations.what3words.words |annotations.wikidata |bounds.northeast.lat |bounds.northeast.lng |bounds.southwest.lat |bounds.southwest.lng |components.ISO_3166-1_alpha-2 |components.ISO_3166-1_alpha-3 |components._category |components._type |components.city |components.continent |components.country |components.country_code |components.political_union |components.state    |components.state_code |confidence |formatted                                                                       | geometry.lat| geometry.lng|annotations.roadinfo.road |components.borough         |components.postcode |components.road  |components.suburb                    |components.tourism |components.county   |components.municipality |components.village |components.hamlet |components.neighbourhood |components.shop |components.historic |components.city_district |components.house_number |components.quarter              |components.town |query  |
|:--------------------|:--------------------|:----------------|:----------------------|:----------------------|:----------------------|:---------------------------------------------------------------------------|:------------------------------------------------------------------------|:-----------------------------------------------------------------------------------|:-----------------------------|:---------------------------------|:-----------------------------------------|:--------------------------------|:----------------------------------------|:-----------------------|:---------------------------------|:--------------------------------|:-----------------------------|:--------------------------------|:-------------------------|:------------------------------------------|:----------------------------|:------------------------------------|:---------------------------|:---------------------------------|:----------------------------------------|:------------------------|:--------------------|:-----------------|:-----------------------------|:-----------------------------|:-----------------------------|:---------------------------------|:--------------------------|:-----------------------------|:----------------------------|:--------------------------------|:-------------------------|:----------------------------|:-------------------------|:-------------------------------|:-------------------------------|:----------------------------------|:-------------------------------|:----------------------------|:--------------------|:--------------------|:--------------------|:--------------------|:--------------------|:-----------------------------|:-----------------------------|:--------------------|:----------------|:---------------|:--------------------|:------------------|:-----------------------|:--------------------------|:-------------------|:---------------------|:----------|:-------------------------------------------------------------------------------|------------:|------------:|:-------------------------|:--------------------------|:-------------------|:----------------|:------------------------------------|:------------------|:-------------------|:-----------------------|:------------------|:-----------------|:------------------------|:---------------|:-------------------|:------------------------|:-----------------------|:-------------------------------|:---------------|:------|
|52° 31' 1.33140'' N  |13° 23' 19.89564'' E |33UUU9067619766  |JO62qm64pc             |1490441.066            |6860227.862            |https://www.openstreetmap.org/edit?relation=62422#map=16/52.51704/13.38886  |https://www.openstreetmap.org/note/new#map=16/52.51704/13.38886&layers=N |https://www.openstreetmap.org/?mlat=52.51704&mlon=13.38886#map=16/52.51704/13.38886 |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u33db8mmzj1t355u0c0j |136.66            |right                         |km/h                          |1601961480                    |1601954640                        |1601959440                 |1601957040                    |1602001800                   |1602008640                       |1602003840                |1602006240                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |nirgends.digitalen.landkarte |Q64                  |52.6755087           |13.7611609           |52.3382448           |13.088345            |DE                            |DEU                           |place                |city             |Berlin          |Europe               |Deutschland        |de                      |European Union             |Berlin              |BE                    |2          |Berlin, Deutschland                                                             |     52.51704|    13.388860|NA                        |NA                         |NA                  |NA               |NA                                   |NA                 |NA                  |NA                      |NA                 |NA                |NA                       |NA              |NA                  |NA                       |NA                      |NA                              |NA              |Berlin |
|52° 30' 12.24072'' N |13° 20' 19.09428'' E |33UUU8723418327  |JO62qm00pt             |1484850.312            |6857739.929            |https://www.openstreetmap.org/edit?node=313826576#map=16/52.50340/13.33864  |https://www.openstreetmap.org/note/new#map=16/52.50340/13.33864&layers=N |https://www.openstreetmap.org/?mlat=52.50340&mlon=13.33864#map=16/52.50340/13.33864 |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u336xtbykz0vehy92f44 |136.58            |right                         |km/h                          |1601961480                    |1601954640                        |1601959440                 |1601957040                    |1602001860                   |1602008640                       |1602003840                |1602006240                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |unbewusst.abbrechen.neuerung |Q4783389             |52.5034502           |13.3386873           |52.5033502           |13.3385873           |DE                            |DEU                           |unknown              |borough          |Berlin          |Europe               |Deutschland        |de                      |European Union             |Berlin              |BE                    |9          |Charlottenburg-Wilmersdorf, Berlin, Tauentzienstraße, 10789 Berlin, Deutschland |     52.50340|    13.338637|Tauentzienstraße          |Charlottenburg-Wilmersdorf |10789               |Tauentzienstraße |Charlottenburg                       |Berlin             |NA                  |NA                      |NA                 |NA                |NA                       |NA              |NA                  |NA                       |NA                      |NA                              |NA              |Berlin |
|54° 2' 10.89780'' N  |10° 26' 46.07268'' E |32UNE9470788534  |JO54fa38mr             |1162858.017            |7142435.831            |https://www.openstreetmap.org/edit?node=50798110#map=16/54.03636/10.44613   |https://www.openstreetmap.org/note/new#map=16/54.03636/10.44613&layers=N |https://www.openstreetmap.org/?mlat=54.03636&mlon=10.44613#map=16/54.03636/10.44613 |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u1x7mtn8se8n18vzuczv |134.07            |right                         |km/h                          |1601962260                    |1601955180                        |1601960160                 |1601957700                    |1602002460                   |1602009480                       |1602004560                |1602007020                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |zusehen.sicht.besucht        |Q12053136            |54.0563605           |10.4661313           |54.0163605           |10.4261313           |DE                            |DEU                           |place                |village          |NA              |Europe               |Deutschland        |de                      |European Union             |Schleswig-Holstein  |SH                    |7          |23823 Berlin, Deutschland                                                       |     54.03636|    10.446131|NA                        |NA                         |23823               |NA               |NA                                   |NA                 |Segeberg            |Trave-Land              |Berlin             |NA                |NA                       |NA              |NA                  |NA                       |NA                      |NA                              |NA              |Berlin |
|54° 24' 18.42840'' N |9° 25' 55.18776'' E  |32UNF2804128682  |JO44rj17uf             |1049965.059            |7212486.314            |https://www.openstreetmap.org/edit?way=68276512#map=16/54.40512/9.43200     |https://www.openstreetmap.org/note/new#map=16/54.40512/9.43200&layers=N  |https://www.openstreetmap.org/?mlat=54.40512&mlon=9.43200#map=16/54.40512/9.43200   |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u1wtw8hhv3q2jjmfesu3 |133.07            |right                         |km/h                          |1601962500                    |1601955360                        |1601960400                 |1601957880                    |1602002640                   |1602009780                       |1602004800                |1602007260                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |niedrig.sicher.kranz         |NA                   |54.4069751           |9.4342708            |54.4029778           |9.4299614            |DE                            |DEU                           |road                 |road             |NA              |Europe               |Deutschland        |de                      |European Union             |Schleswig-Holstein  |SH                    |9          |Berlin, 24848 Klein Bennebek, Deutschland                                       |     54.40512|     9.431997|Berlin                    |NA                         |24848               |Berlin           |NA                                   |NA                 |Schleswig-Flensburg |Kropp-Stapelholm        |Klein Bennebek     |Potsdam           |NA                       |NA              |NA                  |NA                       |NA                      |NA                              |NA              |Berlin |
|52° 25' 7.43664'' N  |13° 11' 47.05872'' E |33UUU7734509142  |JO62ok30nl             |1469017.107            |6842309.679            |https://www.openstreetmap.org/edit?node=1069490670#map=16/52.41873/13.19641 |https://www.openstreetmap.org/note/new#map=16/52.41873/13.19641&layers=N |https://www.openstreetmap.org/?mlat=52.41873&mlon=13.19641#map=16/52.41873/13.19641 |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u336hq934xbyt1e6fspy |136.31            |right                         |km/h                          |1601961480                    |1601954700                        |1601959440                 |1601957100                    |1602001860                   |1602008640                       |1602003900                |1602006240                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |kündbar.nüsse.kellner        |NA                   |52.4187824           |13.1964552           |52.4186824           |13.1963552           |DE                            |DEU                           |unknown              |borough          |Berlin          |Europe               |Deutschland        |de                      |European Union             |Berlin              |BE                    |9          |Steglitz-Zehlendorf, Berlin, A 115, 14109 Berlin, Deutschland                   |     52.41873|    13.196405|A 115                     |Steglitz-Zehlendorf        |14109               |A 115            |Nikolassee                           |Berlin             |NA                  |NA                      |NA                 |NA                |NA                       |NA              |NA                  |NA                       |NA                      |NA                              |NA              |Berlin |
|52° 31' 15.16908'' N |13° 24' 38.79864'' E |33UUU9217320161  |JO62qm95ha             |1492880.911            |6860929.301            |https://www.openstreetmap.org/edit?node=4389014593#map=16/52.52088/13.41078 |https://www.openstreetmap.org/note/new#map=16/52.52088/13.41078&layers=N |https://www.openstreetmap.org/?mlat=52.52088&mlon=13.41078#map=16/52.52088/13.41078 |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u33dc1jkmc8qt030p2q8 |136.69            |right                         |km/h                          |1601961480                    |1601954640                        |1601959440                 |1601957040                    |1602001800                   |1602008640                       |1602003840                |1602006240                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |kobold.ausdehnen.auch        |NA                   |52.5209303           |13.4108274           |52.5208303           |13.4107274           |DE                            |DEU                           |unknown              |borough          |Berlin          |Europe               |Deutschland        |de                      |European Union             |Berlin              |BE                    |9          |Mitte, Berlin, Gontardstraße, 10178 Berlin, Deutschland                         |     52.52088|    13.410777|Gontardstraße             |Mitte                      |10178               |Gontardstraße    |Mitte                                |NA                 |NA                  |NA                      |NA                 |NA                |Spandauer Vorstadt       |Berlin          |NA                  |NA                       |NA                      |NA                              |NA              |Berlin |
|52° 22' 12.67680'' N |9° 45' 10.62252'' E  |32UND5126202479  |JO42vi08iu             |1085693.506            |6833476.151            |https://www.openstreetmap.org/edit?node=320881943#map=16/52.37019/9.75295   |https://www.openstreetmap.org/note/new#map=16/52.37019/9.75295&layers=N  |https://www.openstreetmap.org/?mlat=52.37019&mlon=9.75295#map=16/52.37019/9.75295   |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u1qcvvtyknx5um9fq9f9 |131.66            |right                         |km/h                          |1601962320                    |1601955540                        |1601960280                 |1601957940                    |1602002700                   |1602009480                       |1602004740                |1602007080                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |greift.zentrum.teilt         |NA                   |52.370238            |9.7530007            |52.370138            |9.7529007            |DE                            |DEU                           |unknown              |historic         |Hannover        |Europe               |Deutschland        |de                      |European Union             |Niedersachsen       |NI                    |9          |Berliner Allee, 30175 Hannover, Deutschland                                     |     52.37019|     9.752951|Berliner Allee            |NA                         |30175               |Berliner Allee   |Südstadt-Bult                        |NA                 |Region Hannover     |NA                      |NA                 |NA                |NA                       |NA              |Berlin              |NA                       |NA                      |NA                              |NA              |Berlin |
|53° 51' 4.53384'' N  |10° 40' 56.93196'' E |32UPE1067368285  |JO53iu14vh             |1189168.356            |7107508.609            |https://www.openstreetmap.org/edit?node=1630863689#map=16/53.85126/10.68248 |https://www.openstreetmap.org/note/new#map=16/53.85126/10.68248&layers=N |https://www.openstreetmap.org/?mlat=53.85126&mlon=10.68248#map=16/53.85126/10.68248 |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u1xd756drf74zwdx76by |134.21            |right                         |km/h                          |1601962200                    |1601955120                        |1601960100                 |1601957640                    |1602002400                   |1602009420                       |1602004500                |1602006900                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |umzug.hübsch.tapfer          |NA                   |53.8513094           |10.6825311           |53.8512094           |10.6824311           |DE                            |DEU                           |unknown              |historic         |Lübeck          |Europe               |Deutschland        |de                      |European Union             |Schleswig-Holstein  |SH                    |9          |Berliner Platz, 23560 Lübeck, Deutschland                                       |     53.85126|    10.682481|Berliner Platz            |NA                         |23560               |Berliner Platz   |Hüxtertor / Mühlentor / Gärtnergasse |NA                 |NA                  |NA                      |NA                 |NA                |NA                       |NA              |Berlin              |Sankt Jürgen             |NA                      |NA                              |NA              |Berlin |
|52° 1' 36.20388'' N  |8° 32' 4.49556'' E   |32UMC6806764112  |JO42ga46dj             |950065.334             |6771253.541            |https://www.openstreetmap.org/edit?node=4320672889#map=16/52.02672/8.53458  |https://www.openstreetmap.org/note/new#map=16/52.02672/8.53458&layers=N  |https://www.openstreetmap.org/?mlat=52.02672&mlon=8.53458#map=16/52.02672/8.53458   |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u1npfpntwhjtjju75d94 |129.77            |right                         |km/h                          |1601962620                    |1601955840                        |1601960580                 |1601958240                    |1602003000                   |1602009720                       |1602005040                |1602007380                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |anwalt.freund.tassen         |NA                   |52.0267733           |8.5346321            |52.0266733           |8.5345321            |DE                            |DEU                           |commerce             |shop             |Bielefeld       |Europe               |Deutschland        |de                      |European Union             |Nordrhein-Westfalen |NW                    |9          |Berlin, Herforder Straße 33, 33602 Bielefeld, Deutschland                       |     52.02672|     8.534582|Herforder Straße          |NA                         |33602               |Herforder Straße |Mitte                                |NA                 |NA                  |NA                      |NA                 |NA                |NA                       |Berlin          |NA                  |NA                       |33                      |NA                              |NA              |Berlin |
|47° 59' 4.71444'' N  |10° 11' 11.83056'' E |32TNU8854215274  |JN57cx26jh             |1133969.307            |6072538.283            |https://www.openstreetmap.org/edit?node=4880207121#map=16/47.98464/10.18662 |https://www.openstreetmap.org/note/new#map=16/47.98464/10.18662&layers=N |https://www.openstreetmap.org/?mlat=47.98464&mlon=10.18662#map=16/47.98464/10.18662 |276                           |150                               |155                                       |001                              |MEDC                                     |49                      |,                                 |&#x20AC;                         |EUR                           |978                              |Euro                      |1                                          |Cent                         |100                                  |€                           |1                                 |.                                        |<U+0001F1E9><U+0001F1EA> |u0x0zz3dv3y07kdqqkqc |127.77            |right                         |km/h                          |1601962020                    |1601955840                        |1601960160                 |1601958000                    |1602002820                   |1602009000                       |1602004680                |1602006780                   |Europe/Berlin             |1                               |7200                            |+0200                              |CEST                            |fahrpreis.weinen.spielt      |NA                   |47.9846929           |10.1866696           |47.9845929           |10.1865696           |DE                            |DEU                           |unknown              |historic         |NA              |Europe               |Deutschland        |de                      |European Union             |Bayern              |BY                    |9          |Berlin, 3, 87700 Memmingen, Deutschland                                         |     47.98464|    10.186620|3                         |NA                         |87700               |3                |Neubruch                             |NA                 |NA                  |NA                      |NA                 |NA                |NA                       |NA              |Berlin              |NA                       |NA                      |Gewerbegebiet Schlachthofstraße |Memmingen       |Berlin |

* `limit`: How many results should be returned (1-100). Default is 10.

* `min_confidence`: an integer from 1-10. Only results with at least this confidence will be returned.

* `no_annotations`: Logical (default FALSE), when TRUE the output will not contain annotations.

* `no_dedupe`: Logical (default FALSE), when TRUE the output will not be deduplicated.

 For more information about the output and the query parameters, see the package documentation, the [API doc](https://geocoder.opencagedata.com/api) and [OpenCage FAQ](https://geocoder.opencagedata.com/faq).

## Caching

The underlying data at OpenCage is updated about once a day. Note that the package uses [memoise](https://github.com/hadley/memoise) with no timeout argument so that results are cached inside an active R session.


```r
system.time(opencage_reverse(latitude = 10, longitude = 10))
#>    user  system elapsed 
#>    0.08    0.00    0.18

system.time(opencage_reverse(latitude = 10, longitude = 10))
#>    user  system elapsed 
#>       0       0       0

memoise::forget(opencage_reverse)
#> [1] TRUE
system.time(opencage_reverse(latitude = 10, longitude = 10))
#>    user  system elapsed 
#>    0.01    0.00    0.13
```

## Privacy

Both functions have a parameter `no_record`. It is `FALSE` by default.

* When `no_record` is `FALSE` a log of the query is made by OpenCage. The company uses them to better generally understand how people are using its service (forward or reverse geocoding, what parts of the world are people most interested in, etc) and for debugging. The overwhelming majority (99.9999+% of queries) are never specifically looked at (sheer volume prevents that) and are automatically deleted after a few days. More information about privacy can be found [here](https://geocoder.opencagedata.com/faq#legal).

* When `no_record` is `TRUE` the actual query is replaced with FILTERED in OpenCage logs, so that the company has no chance to see what your request was.

## Addresses

They also have an `abbr` parameter, FALSE by default. When it is TRUE the addresses are abbreviated in the results, see more details in [this blog post](http://blog.opencagedata.com/post/160294347883/shrtr-pls).

## Return query text

The OpenCage API includes an optional `add_request` parameter that when set to 1
the query text is added to the response. This argument is set to TRUE by default,
which allows for easy merging of the response data and the orignal query text.
